// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ewsys_error_code.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Bian {

  /// <summary>Holder for reflection information generated from ewsys_error_code.proto</summary>
  public static partial class EwsysErrorCodeReflection {

    #region Descriptor
    /// <summary>File descriptor for ewsys_error_code.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EwsysErrorCodeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZld3N5c19lcnJvcl9jb2RlLnByb3RvEgRCaWFuKvcICgtFd0Vycm9yQ29k",
            "ZRIbChdFd0Vycm9yQ29kZV9FRUNfVW5rbm93bhAAEjEKJEVFQ19DbGllbnRf",
            "U3RhcnRVcF9OYXRpdmVTZXJ2ZXJfRmFpbBDvsf////////8BEigKG0VFQ19D",
            "bGllbnRfTG9hZEFjY291bnRfRmFpbBDusf////////8BEiQKF0VFQ19DbGll",
            "bnRfTG9hZE1hcF9GYWlsEO2x/////////wESJQoYRUVDX0NsaWVudF9DcmVh",
            "dE1hcF9GYWlsEOyx/////////wESJQoYRUVDX0NsaWVudF9Kb2luUm9vbV9G",
            "YWlsEOux/////////wESKQocRUVDX0NsaWVudF9Mb2FkUm9sZUluZm9fRmFp",
            "bBDqsf////////8BEicKGkVFQ19DbGllbnRfTG9hZENvbmZpZ19GYWlsEOmx",
            "/////////wESKwoeRUVDX0NsaWVudF9Mb2FkTGVzc29uRGF0YV9GYWlsEOix",
            "/////////wESLwoiRUVDX0NsaWVudF9Kb2luX0xlc3NvblNlY3Rpb25fRmFp",
            "bBDnsf////////8BEjEKJEVFQ19DbGllbnRfQ29ubmVjdF9OYXRpdmVTZXJ2",
            "ZXJfRmFpbBDmsf////////8BEi8KIkVFQ19DbGllbnRfTmF0aXZlU2VydmVy",
            "X05vUnNwX0ZhaWwQ5bH/////////ARIvCiJFRUNfU2VydmVyX1N0YXJ0VXBf",
            "R2FtZVNlcnZlcl9GYWlsEN/j/v///////wESKAobRUVDX1NlcnZlcl9Mb2Fk",
            "QWNjb3VudF9GYWlsEN7j/v///////wESJAoXRUVDX1NlcnZlcl9Mb2FkTWFw",
            "X0ZhaWwQ3eP+////////ARIlChhFRUNfU2VydmVyX0NyZWF0TWFwX0ZhaWwQ",
            "3OP+////////ARIlChhFRUNfU2VydmVyX0pvaW5Sb29tX0ZhaWwQ2+P+////",
            "////ARIpChxFRUNfU2VydmVyX0xvYWRSb2xlSW5mb19GYWlsENrj/v//////",
            "/wESJwoaRUVDX1NlcnZlcl9Mb2FkQ29uZmlnX0ZhaWwQ2eP+////////ARIu",
            "CiFFRUNfUGxhdGZvcm1fU3RhcnRVcF9NYXBIYWxsX0ZhaWwQz5X+////////",
            "ARIuCiFFRUNfUGxhdGZvcm1fU3RhcnRVcF9BY2NvdW50X0ZhaWwQzpX+////",
            "////ARItCiBFRUNfUGxhdGZvcm1fU3RhcnRVcF9CYW5uZXJfRmFpbBDNlf7/",
            "//////8BEioKHUVFQ19QbGF0Zm9ybV9Mb2FkQWNjb3VudF9GYWlsEMyV/v//",
            "/////wESLgohRUVDX1BsYXRmb3JtX0NyZWF0U2VydmVyTm9kZV9GYWlsEMuV",
            "/v///////wESKwoeRUVDX1BsYXRmb3JtX0xvYWRSb2xlSW5mb19GYWlsEMqV",
            "/v///////wESKQocRUVDX1BsYXRmb3JtX0xvYWRDb25maWdfRmFpbBDJlf7/",
            "//////8BYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Bian.EwErrorCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EwErrorCode {
    /// <summary>
    /// -------------------------------------------------------------------------
    /// 预警上送的错误类型码，文档中每定义一个补齐一个， 保持定义对应
    /// </summary>
    [pbr::OriginalName("EwErrorCode_EEC_Unknown")] EecUnknown = 0,
    /// <summary>
    ///******    -10001  ~ -20000  客户端错误码范围 ******
    /// </summary>
    [pbr::OriginalName("EEC_Client_StartUp_NativeServer_Fail")] EecClientStartUpNativeServerFail = -10001,
    /// <summary>
    ///  客户端加载账号信息失败
    /// </summary>
    [pbr::OriginalName("EEC_Client_LoadAccount_Fail")] EecClientLoadAccountFail = -10002,
    /// <summary>
    ///  客户端加载地图数据失败
    /// </summary>
    [pbr::OriginalName("EEC_Client_LoadMap_Fail")] EecClientLoadMapFail = -10003,
    /// <summary>
    ///  客户端创建地图失败
    /// </summary>
    [pbr::OriginalName("EEC_Client_CreatMap_Fail")] EecClientCreatMapFail = -10004,
    /// <summary>
    ///  客户端进入房间失败
    /// </summary>
    [pbr::OriginalName("EEC_Client_JoinRoom_Fail")] EecClientJoinRoomFail = -10005,
    /// <summary>
    ///  客户端加载角色信息失败
    /// </summary>
    [pbr::OriginalName("EEC_Client_LoadRoleInfo_Fail")] EecClientLoadRoleInfoFail = -10006,
    /// <summary>
    ///  客户端加载配置文件失败
    /// </summary>
    [pbr::OriginalName("EEC_Client_LoadConfig_Fail")] EecClientLoadConfigFail = -10007,
    /// <summary>
    ///  客户端加载课程数据失败
    /// </summary>
    [pbr::OriginalName("EEC_Client_LoadLessonData_Fail")] EecClientLoadLessonDataFail = -10008,
    /// <summary>
    ///  客户端进入课程章节失败
    /// </summary>
    [pbr::OriginalName("EEC_Client_Join_LessonSection_Fail")] EecClientJoinLessonSectionFail = -10009,
    /// <summary>
    ///  客户端连接 NativeServer失败
    /// </summary>
    [pbr::OriginalName("EEC_Client_Connect_NativeServer_Fail")] EecClientConnectNativeServerFail = -10010,
    /// <summary>
    ///  客户端请求 NativeServer消息无回应
    /// </summary>
    [pbr::OriginalName("EEC_Client_NativeServer_NoRsp_Fail")] EecClientNativeServerNoRspFail = -10011,
    /// <summary>
    ///******    -20001  ~ -30000  服务端错误码范围 ******
    /// </summary>
    [pbr::OriginalName("EEC_Server_StartUp_GameServer_Fail")] EecServerStartUpGameServerFail = -20001,
    /// <summary>
    ///  服务器加载账号信息失败
    /// </summary>
    [pbr::OriginalName("EEC_Server_LoadAccount_Fail")] EecServerLoadAccountFail = -20002,
    /// <summary>
    ///  服务器加载地图失败
    /// </summary>
    [pbr::OriginalName("EEC_Server_LoadMap_Fail")] EecServerLoadMapFail = -20003,
    /// <summary>
    ///  服务器创建地图失败
    /// </summary>
    [pbr::OriginalName("EEC_Server_CreatMap_Fail")] EecServerCreatMapFail = -20004,
    /// <summary>
    ///  玩家进入房间失败
    /// </summary>
    [pbr::OriginalName("EEC_Server_JoinRoom_Fail")] EecServerJoinRoomFail = -20005,
    /// <summary>
    ///  服务器加载角色信息失败
    /// </summary>
    [pbr::OriginalName("EEC_Server_LoadRoleInfo_Fail")] EecServerLoadRoleInfoFail = -20006,
    /// <summary>
    ///  服务器加载配置文件失败
    /// </summary>
    [pbr::OriginalName("EEC_Server_LoadConfig_Fail")] EecServerLoadConfigFail = -20007,
    /// <summary>
    ///******    -30001  ~ -40000  平台服务器错误码范围(hall,accout等) ******
    /// </summary>
    [pbr::OriginalName("EEC_Platform_StartUp_MapHall_Fail")] EecPlatformStartUpMapHallFail = -30001,
    /// <summary>
    ///  平台启动Account server失败
    /// </summary>
    [pbr::OriginalName("EEC_Platform_StartUp_Account_Fail")] EecPlatformStartUpAccountFail = -30002,
    /// <summary>
    ///  平台启动Banner server失败
    /// </summary>
    [pbr::OriginalName("EEC_Platform_StartUp_Banner_Fail")] EecPlatformStartUpBannerFail = -30003,
    /// <summary>
    ///  平台查询账号信息 失败
    /// </summary>
    [pbr::OriginalName("EEC_Platform_LoadAccount_Fail")] EecPlatformLoadAccountFail = -30004,
    /// <summary>
    ///  平台创建云端game失败
    /// </summary>
    [pbr::OriginalName("EEC_Platform_CreatServerNode_Fail")] EecPlatformCreatServerNodeFail = -30005,
    /// <summary>
    ///  平台加载角色信息失败
    /// </summary>
    [pbr::OriginalName("EEC_Platform_LoadRoleInfo_Fail")] EecPlatformLoadRoleInfoFail = -30006,
    /// <summary>
    ///  平台加载配置文件失败
    /// </summary>
    [pbr::OriginalName("EEC_Platform_LoadConfig_Fail")] EecPlatformLoadConfigFail = -30007,
  }

  #endregion

}

#endregion Designer generated code
