// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: server_event.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MelandGame3 {

  /// <summary>Holder for reflection information generated from server_event.proto</summary>
  public static partial class ServerEventReflection {

    #region Descriptor
    /// <summary>File descriptor for server_event.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServerEventReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJzZXJ2ZXJfZXZlbnQucHJvdG8SC01lbGFuZEdhbWUzKt8BChJTZXJ2ZXJN",
            "c2dFdmVudFR5cGUSLworU2VydmVyTXNnRXZlbnRUeXBlX1NlcnZlck1zZ0V2",
            "ZW50VHlwZVVua25vdxAAEjMKL1NlcnZlck1zZ0V2ZW50VHlwZV9TZXJ2ZXJN",
            "c2dFdmVudFR5cGVSZWNlaXZlTXNnEAESMQotU2VydmVyTXNnRXZlbnRUeXBl",
            "X1NlcnZlck1zZ0V2ZW50VHlwZUNhbGxCYWNrEAISMAosU2VydmVyTXNnRXZl",
            "bnRUeXBlX1NlcnZlck1zZ0V2ZW50VHlwZVRpbWVPdXQQAyr/JQoPU2VydmVy",
            "RXZlbnRUeXBlEjAKLFNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFR5cGVT",
            "ZXJ2ZXJVbmtub3duEAASNAowU2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50",
            "VHlwZVNlcnZlckFmdGVyQ29uZmlnEAoSMQotU2VydmVyRXZlbnRUeXBlX1Nl",
            "cnZlckV2ZW50VHlwZVNlcnZlck1pbnV0ZWx5EAsSLworU2VydmVyRXZlbnRU",
            "eXBlX1NlcnZlckV2ZW50VHlwZVNlcnZlckhvdXJseRAMEi4KKlNlcnZlckV2",
            "ZW50VHlwZV9TZXJ2ZXJFdmVudFR5cGVTZXJ2ZXJEYWlseRANEjIKLlNlcnZl",
            "ckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFR5cGVTZXJ2ZXJDb25uQ2xvc2UQDhI0",
            "CjBTZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRUeXBlU2VydmVyQ29ubkNv",
            "bm5lY3QQDxIuCipTZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRUeXBlU2Vy",
            "dmVyVGltZXIQEBIuCipTZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRUeXBl",
            "U3FsUm9sbEJhY2sQERIyCi5TZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRU",
            "eXBlU2VydmVyRXZlbnRDYWxsEBISMAosU2VydmVyRXZlbnRUeXBlX1NlcnZl",
            "ckV2ZW50VHlwZVBsYXllckNyZWF0ZWQQZBIvCitTZXJ2ZXJFdmVudFR5cGVf",
            "U2VydmVyRXZlbnRUeXBlUGxheWVyT25saW5lEGUSMAosU2VydmVyRXZlbnRU",
            "eXBlX1NlcnZlckV2ZW50VHlwZVBsYXllck9mZmxpbmUQZhIvCitTZXJ2ZXJF",
            "dmVudFR5cGVfU2VydmVyRXZlbnRUeXBlUGxheWVyTmV3RGF5EGcSLQopU2Vy",
            "dmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50VHlwZVBsYXllckx2VXAQaBI1CjFT",
            "ZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRUeXBlUGxheWVyUmVzZXRQcm9m",
            "aWxlEGkSNAowU2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50VHlwZVBsYXll",
            "clVwZGF0ZVNraWxsEGoSLworU2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50",
            "VHlwZVBsYXllckFkZEV4cBBrEjAKLFNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJF",
            "dmVudFR5cGVQbGF5ZXJSZXBseUhwEGwSMAosU2VydmVyRXZlbnRUeXBlX1Nl",
            "cnZlckV2ZW50VHlwZVVubG9ja0Zvcm11bGEQbRI5CjVTZXJ2ZXJFdmVudFR5",
            "cGVfU2VydmVyRXZlbnRUeXBlQ2FsY3VsYXRlUGxheWVyUHJvZmlsZRBuEjEK",
            "LVNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFR5cGVQbGF5ZXJVc2VTa2ls",
            "bBBvEjEKLVNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFR5cGVQbGF5ZXJC",
            "ZUF0dGFjaxBwEi4KKlNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFR5cGVE",
            "ZXN0b3J5SXRlbRByEjEKLVNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFR5",
            "cGVEZXN0b3J5QWxsSXRlbRBzEioKJlNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJF",
            "dmVudFR5cGVBZGRJdGVtEHQSLgoqU2VydmVyRXZlbnRUeXBlX1NlcnZlckV2",
            "ZW50VHlwZVJlZGVlbUNES2V5EHUSKgomU2VydmVyRXZlbnRUeXBlX1NlcnZl",
            "ckV2ZW50VHlwZUR1bmdlb24QdhIuCipTZXJ2ZXJFdmVudFR5cGVfU2VydmVy",
            "RXZlbnRUeXBlU2VuZENoYXRNc2cQdxI2CjJTZXJ2ZXJFdmVudFR5cGVfU2Vy",
            "dmVyRXZlbnRUeXBlU2VuZFVwZGF0ZUNoYXRTdGF0ZRB4EjQKMFNlcnZlckV2",
            "ZW50VHlwZV9TZXJ2ZXJFdmVudFR5cGVTZW5kUmVtb3ZlQ2hhdE1zZxB5EjAK",
            "K1NlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFpvbmVTZW5kVG9QbGF5ZXIQ",
            "yAESJQogU2VydmVyRXZlbnRUeXBlX1oyU1pvbmVCcm9hZGNhc3QQygESNQow",
            "U2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50RW50aXR5QW5pbWF0aW9uQ3Jl",
            "YXRlEMsBEjUKMFNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudEVudGl0eUFu",
            "aW1hdGlvblVwZGF0ZRDMARIyCi1TZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZl",
            "bnRFbnRpdHlBbmltYXRpb25EZWwQzQESIgodU2VydmVyRXZlbnRUeXBlX1oy",
            "U0dvYk1hcFNhdmUQzgESMgotU2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50",
            "RW50aXR5UGxheWVyVXBkYXRlEM8BEioKJVNlcnZlckV2ZW50VHlwZV9aMlNF",
            "bnRpdHlUZW1wbGF0ZVNhdmUQ0AESJQogU2VydmVyRXZlbnRUeXBlX1oyU1Bs",
            "YXllck9mZmxpbmUQ0gESJwoiU2VydmVyRXZlbnRUeXBlX1oyU1BsYXllck1h",
            "bm9yRGF0YRDTARIqCiVTZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRFbnRp",
            "dHlTYXZlENUBEiMKHlNlcnZlckV2ZW50VHlwZV9aMlNCdWlsZERlbGV0ZRDy",
            "ARIlCiBTZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRCdWlsZBDzARIkCh9T",
            "ZXJ2ZXJFdmVudFR5cGVfWjJTUHVwcGV0RGVsZXRlEPQBEiIKHVNlcnZlckV2",
            "ZW50VHlwZV9aMlNQbGF5ZXJTYXZlEI8DEiIKHVNlcnZlckV2ZW50VHlwZV9a",
            "MlNFbnRpdHlTYXZlEJADEiMKHlNlcnZlckV2ZW50VHlwZV9aMlNNYW5vclBh",
            "Y2tldBCRAxIrCiZTZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRDb2RlRXhl",
            "Y3V0ZRD0AxIvCipTZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRVc2VJdGVt",
            "RnJvbVpvbmUQ9QMSMAorU2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50RHJv",
            "cEl0ZW1Gcm9tWm9uZRD2AxIwCitTZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZl",
            "bnRCb3RCdWlsZEZyb21ab25lEPcDEjAKK1NlcnZlckV2ZW50VHlwZV9TZXJ2",
            "ZXJFdmVudE1ha2VJdGVtRnJvbVpvbmUQ+QMSPgo5U2VydmVyRXZlbnRUeXBl",
            "X1NlcnZlckV2ZW50VGFrZVdvcmtiZW5jaEl0ZW1CeUNpZEZyb21ab25lEPoD",
            "Ej4KOVNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudEdpdmVXb3JrYmVuY2hJ",
            "dGVtQnlDaWRGcm9tWm9uZRD7AxI1CjBTZXJ2ZXJFdmVudFR5cGVfU2VydmVy",
            "RXZlbnRQbGF5ZXJDb21wbGV0ZUNoYXB0ZXIQ/AMSLAonU2VydmVyRXZlbnRU",
            "eXBlX1NlcnZlckV2ZW50TWlzc2lvbkVudGVyEP0DEioKJVNlcnZlckV2ZW50",
            "VHlwZV9TZXJ2ZXJFdmVudEFjY2VwdFRhc2sQ/gMSKgolU2VydmVyRXZlbnRU",
            "eXBlX1NlcnZlckV2ZW50U3VibWl0VGFzaxD/AxIsCidTZXJ2ZXJFdmVudFR5",
            "cGVfU2VydmVyRXZlbnRDb21wbGF0ZVRhc2sQgAQSOAozU2VydmVyRXZlbnRU",
            "eXBlX1NlcnZlckV2ZW50TWlzc2lvbkVudGVyU2NlbmVNb25pdG9yEIEEEiMK",
            "HlNlcnZlckV2ZW50VHlwZV9aMlNfUGxheWVyRGVhZBDIBRIuCilTZXJ2ZXJF",
            "dmVudFR5cGVfU2VydmVyRXZlbnRaMlNBZGRFeHBUb0JvdBDLBRIqCiVTZXJ2",
            "ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRaMlNCb3REZWFkENsFEiMKHlNlcnZl",
            "ckV2ZW50VHlwZV9aMlNQbGFudERlbGV0ZRDxBRIhChxTZXJ2ZXJFdmVudFR5",
            "cGVfWjJTUGV0RGVsZXRlEPIFEi4KKVNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJF",
            "dmVudFR5cGVCb3RDcmVhdGVkEKAGEisKJlNlcnZlckV2ZW50VHlwZV9TZXJ2",
            "ZXJFdmVudFR5cGVCb3RMdlVwEKEGEjYKMVNlcnZlckV2ZW50VHlwZV9TZXJ2",
            "ZXJFdmVudFR5cGVVcGRhdGVCb3RFcXVpcG1lbnQQogYSLQooU2VydmVyRXZl",
            "bnRUeXBlX1NlcnZlckV2ZW50VHlwZUJvdEFkZEV4cBCjBhIuCilTZXJ2ZXJF",
            "dmVudFR5cGVfU2VydmVyRXZlbnRUeXBlQm90UmVwbHlIcBCkBhIwCitTZXJ2",
            "ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRUeXBlQm90QWRkT2JqZWN0EKUGEi0K",
            "KFNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFR5cGVSZWNhbGxCb3QQpgYS",
            "LwoqU2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50VHlwZUJvdFVzZVNraWxs",
            "EKcGEi8KKlNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFR5cGVCb3RCZUF0",
            "dGFjaxCoBhIuCilTZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRUeXBlQm90",
            "QWRkSXRlbRCpBhI3CjJTZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRUeXBl",
            "UGxheWVyVXNlQ29uc3VtYWJsZRCGBxIzCi5TZXJ2ZXJFdmVudFR5cGVfU2Vy",
            "dmVyRXZlbnRUeXBlUGxheWVyQWRkT2JqZWN0EIcHEiMKHlNlcnZlckV2ZW50",
            "VHlwZV9aMlNQaWNrRmFsbGluZxCIBxImCiFTZXJ2ZXJFdmVudFR5cGVfWjJT",
            "UGlja0ZhbGxpbmdCb3gQiQcSMwouU2VydmVyRXZlbnRUeXBlX1NlcnZlckV2",
            "ZW50VHlwZVBsYXllclVzZU9iamVjdBCLBxI6CjVTZXJ2ZXJFdmVudFR5cGVf",
            "U2VydmVyRXZlbnRUeXBlQWRkSXRlbUJ5T3BlcmF0ZUJ1YmJsZRCMBxI7CjZT",
            "ZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRUeXBlVGFrZUl0ZW1CeU9wZXJh",
            "dGVCdWJibGUQjQcSPgo5U2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50VHlw",
            "ZVJlcGxhY2VJdGVtQnlPcGVyYXRlQnViYmxlEI4HEjgKM1NlcnZlckV2ZW50",
            "VHlwZV9TZXJ2ZXJFdmVudFR5cGVSZXNldFBsYXllck5mdFN0YXR1cxCPBxI0",
            "Ci9TZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRUeXBlVXBkYXRlUGxheWVy",
            "TkZUcxCQBxI5CjRTZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRUeXBlVXBk",
            "YXRlVGhpcmROZnRUaW1lT3V0EJMHEjYKMVNlcnZlckV2ZW50VHlwZV9TZXJ2",
            "ZXJFdmVudFR5cGVQbGF5ZXJBY2NlcHRlZFRhc2sQ6QcSNwoyU2VydmVyRXZl",
            "bnRUeXBlX1NlcnZlckV2ZW50VHlwZVBsYXllclN1Ym1pdHRlZFRhc2sQ6gcS",
            "Owo2U2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50VHlwZVVwZGF0ZU5wY1Rh",
            "c2tOb3RpY2VUeXBlEOsHEjkKNFNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVu",
            "dFR5cGVQbGF5ZXJUYXNrU3RhdGVVcGRhdGUQ7QcSMgotU2VydmVyRXZlbnRU",
            "eXBlX1NlcnZlckV2ZW50VGFza1Byb2dyZXNzQ2hhbmdlEJkIEjEKLFNlcnZl",
            "ckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFR5cGVQbGF5ZXJBZGRNYWlsEJsIEj4K",
            "OVNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFR5cGVTZXJ2ZXJTZW5kTWFp",
            "bEJ5VGVtcGxhdGVJZBCcCBIzCi5TZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZl",
            "bnRUeXBlTGFuZEdyb3VwQ3JlYXRlEKhGEjMKLlNlcnZlckV2ZW50VHlwZV9T",
            "ZXJ2ZXJFdmVudFR5cGVMYW5kR3JvdXBVcGRhdGUQqUYSMwouU2VydmVyRXZl",
            "bnRUeXBlX1NlcnZlckV2ZW50VHlwZUxhbmRHcm91cFJlbW92ZRCqRhIrCiVT",
            "ZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRUeXBlTnVtTWF4EP//AyqcJQoO",
            "V29ybGRFdmVudFR5cGUSKAokV29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5",
            "cGVVbmtub3duEAASKwonV29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVT",
            "ZW5kVG9ab25lEAESKQolV29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVF",
            "bnRlck1hcBACEikKJVdvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlTGVh",
            "dmVNYXAQAxIlCiFXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZU1vdmUQ",
            "BBIoCiRXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZU1hcFNhdmUQBRI0",
            "CjBXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZVJlbG9hZFJlc291cmNl",
            "UG9pbnQQBhIvCitXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZUluaXRN",
            "YXBFbGVtZW50EAcSKwonV29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVF",
            "bnRpdHlTYXZlEAgSLAooV29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVQ",
            "bGF5ZXJSZXNldBAJEi8KK1dvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBl",
            "UmVzZXRBcmVhU3RhdGUQChIzCi9Xb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50",
            "VHlwZURpdXJuYWxDeWNsZUNoYW5nZRAeEjAKLFdvcmxkRXZlbnRUeXBlX1dv",
            "cmxkRXZlbnRUeXBlRW50aXR5RXZlbnRDYWxsEGUSNQoxV29ybGRFdmVudFR5",
            "cGVfV29ybGRFdmVudFR5cGVBZGRFbnRpdHlUb0NodW5rR3JpZBBmEioKJldv",
            "cmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlR2V0RW50aXR5EGgSOAo0V29y",
            "bGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVFbnRpdHlFdmVudENhbGxOb1Jl",
            "dHVybhBpEjwKOFdvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlUmVzdGFy",
            "dEFsbEVudGl0aWVzQ29kZUJsb2NrEGoSMwovV29ybGRFdmVudFR5cGVfV29y",
            "bGRFdmVudFR5cGVSZXNvdXJjZUxvYWRGaW5pc2gQaxIxCi1Xb3JsZEV2ZW50",
            "VHlwZV9Xb3JsZEV2ZW50VHlwZVVwZGF0ZVdpZGdldEF0dHIQbBI5CjVXb3Js",
            "ZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZVJ1bkNvZGVCbG9ja0J5UGxheWVy",
            "QXJlYRBtEjkKNVdvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlRW50aXRp",
            "ZXNSZXN0YXJ0Q29kZUJsb2NrEG4SNgoyV29ybGRFdmVudFR5cGVfV29ybGRF",
            "dmVudFR5cGVQdWJsaWNBcmVhUmVzdGFydENvZGUQcBI2CjJXb3JsZEV2ZW50",
            "VHlwZV9Xb3JsZEV2ZW50VHlwZVBsYXllckFyZWFSZXN0YXJ0Q29kZRBxEjMK",
            "L1dvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlUmVtb3ZlRW50aXR5Q2hh",
            "bmdlEHISLQopV29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVSZXZpdmVF",
            "bnRpdHkQcxIyCi5Xb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZVJlc3Rh",
            "cnREdW5nZW9uTWFwEHQSOgo2V29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5",
            "cGVFbnRpdGllc0V4ZWN1dGVTdGFydEV2ZW50EHUSNgoyV29ybGRFdmVudFR5",
            "cGVfV29ybGRFdmVudFR5cGVFbnRpdGllc1N0b3BDb2RlQmxvY2sQdhI0CjBX",
            "b3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZUFwcGx5RW50aXR5VGVtcGxh",
            "dGUQeBI1CjFXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZUFkZENhbWVy",
            "YVRvQ2h1bmtHcmlkEHkSNAowV29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5",
            "cGVab25lQXJlYVJlc3RhcnRDb2RlEHoSQAo8V29ybGRFdmVudFR5cGVfV29y",
            "bGRFdmVudFR5cGVBZGRFbnRpdHlXaXRob3V0Vmlld1RvQ2h1bmtHcmlkEHsS",
            "NgoyV29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVDb2RlRXZlbnROb3Rp",
            "ZmljYXRpb24QfBI5CjVXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZVB1",
            "YmxpY0FyZWFSZXNldENvZGVCbG9jaxB9EkMKP1dvcmxkRXZlbnRUeXBlX1dv",
            "cmxkRXZlbnRUeXBlRW50aXRpZXNFeGVjdXRlUXVpY2tDb2RlU3RhcnRFdmVu",
            "dBB+EjwKOFdvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlUmVzZXRFbnRp",
            "dGllc1F1aWNrQ29kZVN0YXRlEH8SOwo2V29ybGRFdmVudFR5cGVfV29ybGRF",
            "dmVudFR5cGVFbnRpdGllc1F1aWNrQ29kZVRhYkRhdGFzEIABEi0KKFdvcmxk",
            "RXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlVG9HcmlkRXZlbnQQlgESKwomV29y",
            "bGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVab29tRXZlbnQQlwESMQosV29y",
            "bGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVQbGF5ZXJBZGRFbnRpdHkQyQES",
            "MQosV29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVQbGF5ZXJEZWxFbnRp",
            "dHkQygESMgotV29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVQbGF5ZXJN",
            "b3ZlRW50aXR5EMsBEi4KKVdvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBl",
            "Qm90QWRkRW50aXR5EMwBEjgKM1dvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRU",
            "eXBlUGxheWVyRGVsRW50aXR5QnlTY2VuZRDNARI4CjNXb3JsZEV2ZW50VHlw",
            "ZV9Xb3JsZEV2ZW50VHlwZVBsYXllckFkZFJlc291cmNlUG9pbnQQ0gESOAoz",
            "V29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVQbGF5ZXJEZWxSZXNvdXJj",
            "ZVBvaW50ENMBEjQKL1dvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlUGxh",
            "eWVyQWRkQm9yblBvaW50ENQBEjQKL1dvcmxkRXZlbnRUeXBlX1dvcmxkRXZl",
            "bnRUeXBlUGxheWVyRGVsQm9yblBvaW50ENUBEicKIldvcmxkRXZlbnRUeXBl",
            "X1MyWkxlc3NvbkFyZWFDcmVhdGUQ1gESJAofV29ybGRFdmVudFR5cGVfUzJa",
            "TGVzc29uQXJlYURlbBDXARImCiFXb3JsZEV2ZW50VHlwZV9TMlpMZXNzb25B",
            "cmVhUXVlcnkQ2AESJwoiV29ybGRFdmVudFR5cGVfUzJaTGVzc29uQXJlYVVw",
            "ZGF0ZRDZARInCiJXb3JsZEV2ZW50VHlwZV9TMlpCZWF1dHlBcmVhVXBkYXRl",
            "ENoBEiUKIFdvcmxkRXZlbnRUeXBlX1MyWkxlc3NvbkFyZWFDb3B5ENsBEiwK",
            "J1dvcmxkRXZlbnRUeXBlX1MyWkxlc3NvbkFyZWFJbmRleFVwZGF0ZRDcARIn",
            "CiJXb3JsZEV2ZW50VHlwZV9TMlpMZXNzb25BcmVhVW5sb2NrEN0BEi4KKVdv",
            "cmxkRXZlbnRUeXBlX1MyWkxlc3NvblBsYXllckFycml2ZWRBcmVhEN4BEjIK",
            "LVdvcmxkRXZlbnRUeXBlX1MyWkxlc3NvbkFyZWFSdW5RdWlja0NvZGVTdGFy",
            "dBDfARIwCitXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZUFkZFRpbGVN",
            "YXBTaWduEOABEjMKLldvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlUmVt",
            "b3ZlVGlsZU1hcFNpZ24Q4QESKgolV29ybGRFdmVudFR5cGVfV29ybGRFdmVu",
            "dFR5cGVTcGF3bkJvdBCtAhIrCiZXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50",
            "VHlwZVJlY2FsbEJvdBCuAhItCihXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50",
            "VHlwZUlzc3VlU2V0dGxlEJEDEjAKK1dvcmxkRXZlbnRUeXBlX1dvcmxkRXZl",
            "bnRUeXBlR2V0RW50aXR5SXNzdWUQkgMSNAovV29ybGRFdmVudFR5cGVfV29y",
            "bGRFdmVudFR5cGVXb3JrYmVuY2hVcGRhdGVTdWIQ+gMSNwoyV29ybGRFdmVu",
            "dFR5cGVfV29ybGRFdmVudFR5cGVXb3JrYmVuY2hVcGRhdGVGYXRoZXIQ+wMS",
            "MQosV29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVTcGF3blBhbHllckFy",
            "ZWEQ2AQSMAorV29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVNb3ZlUGFs",
            "eWVyQXJlYRDZBBIyCi1Xb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZVJl",
            "bW92ZVBhbHllckFyZWEQ2gQSMwouV29ybGRFdmVudFR5cGVfV29ybGRFdmVu",
            "dFR5cGVRdWVyeU15UGFseWVyQXJlYRDbBBIuCilXb3JsZEV2ZW50VHlwZV9X",
            "b3JsZEV2ZW50VHlwZVNldEdsb2JhbFZhchDcBBIyCi1Xb3JsZEV2ZW50VHlw",
            "ZV9Xb3JsZEV2ZW50VHlwZVF1ZXJ5UGFseWVyQXJlYXMQ3QQSNQowV29ybGRF",
            "dmVudFR5cGVfV29ybGRFdmVudFR5cGVRdWVyeVBhbHllckFyZWFCeVJjEN4E",
            "Eh8KGldvcmxkRXZlbnRUeXBlX1MyWk1hbm9yQnV5EOIEEicKIldvcmxkRXZl",
            "bnRUeXBlX1MyWk1hbm9yQnV5TWFya1N5bmMQ4wQSKgolV29ybGRFdmVudFR5",
            "cGVfUzJaTWFub3JUZW1wbGF0ZVBhY2tldBDkBBInCiJXb3JsZEV2ZW50VHlw",
            "ZV9TMlpNYW5vclRlbXBsYXRlVXNlEOUEEjkKNFdvcmxkRXZlbnRUeXBlX1dv",
            "cmxkRXZlbnRUeXBlVGVhY2hlclJlc2V0UHVibGljTWFub3IQ5gQSNgoxV29y",
            "bGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVDcmVhdEFyZWFCeUVtcHR5QXJl",
            "YRDnBBI0Ci9Xb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZU1hbm9yVGVt",
            "cGxhdGVDaGVjaxDoBBI0Ci9Xb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlw",
            "ZUFyZWFVcGRhdGVUZW1wbGF0ZRDpBBItCihXb3JsZEV2ZW50VHlwZV9TMlpQ",
            "bGF5ZXJBcmVhTG9hZE1hbm9yTWFwEOoEEi4KKVdvcmxkRXZlbnRUeXBlX1My",
            "Wk1hbm9yVGVtcGxhdGVDaGFuZ2VTaXplEOsEEioKJVdvcmxkRXZlbnRUeXBl",
            "X1MyWlBsYXllck1hbm9yVGFrZUJhY2sQ7AQSNwoyV29ybGRFdmVudFR5cGVf",
            "V29ybGRFdmVudFR5cGVVcGRhdGVBcmVhUmVjb3ZlclRpbWUQ7QQSJgohV29y",
            "bGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVVbmRvEL0FEiYKIVdvcmxkRXZl",
            "bnRUeXBlX1dvcmxkRXZlbnRUeXBlUmVkbxC+BRI0Ci9Xb3JsZEV2ZW50VHlw",
            "ZV9Xb3JsZEV2ZW50VHlwZUNvZGVibG9ja0FkZEVudGl0eRChBhI0Ci9Xb3Js",
            "ZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZUNvZGVibG9ja0RlbEVudGl0eRCi",
            "BhIrCiZXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZUNsaWVudE1zZxDJ",
            "TBItCihXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZUdtQWRkRW50aXR5",
            "EK1NEj0KOFdvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlUGxheWVyQWRk",
            "QmlnV29ybGRTeXN0ZW1BcmVhEKhGEj0KOFdvcmxkRXZlbnRUeXBlX1dvcmxk",
            "RXZlbnRUeXBlUGxheWVyRGVsQmlnV29ybGRTeXN0ZW1BcmVhEKlGEikKI1dv",
            "cmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlTnVtTWF4EP//AypjCg1Hcmlk",
            "RXZlbnRUeXBlEiYKIkdyaWRFdmVudFR5cGVfR3JpZEV2ZW50VHlwZVVua25v",
            "d24QABIqCiZHcmlkRXZlbnRUeXBlX0dyaWRFdmVudFR5cGVFbnRpdHlFdmVu",
            "dBABKv0tCg9FbnRpdHlFdmVudFR5cGUSKgomRW50aXR5RXZlbnRUeXBlX0Vu",
            "dGl0eUV2ZW50VHlwZVVua25vd24QABIpCiVFbnRpdHlFdmVudFR5cGVfRW50",
            "aXR5RXZlbnRUeXBlTW92ZVRvEAESKwonRW50aXR5RXZlbnRUeXBlX0VudGl0",
            "eUV2ZW50VHlwZVVzZVNraWxsEAISMAosRW50aXR5RXZlbnRUeXBlX0VudGl0",
            "eUV2ZW50VHlwZUNoYW5nZUF2YXRhcnMQAxIwCixFbnRpdHlFdmVudFR5cGVf",
            "RW50aXR5RXZlbnRUeXBlVXBkYXRlUHJvZmlsZRAEEi4KKkVudGl0eUV2ZW50",
            "VHlwZV9FbnRpdHlFdmVudFR5cGVVcGRhdGVTa2lsbBAFEi4KKkVudGl0eUV2",
            "ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVVcGRhdGVMZXZlbBAGEi0KKUVudGl0",
            "eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVSZWNvdmVyeUhwEAcSKwonRW50",
            "aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZVRlbGVwb3J0EAkSLgoqRW50",
            "aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZVBpY2tGYWxsaW5nEAsSKgom",
            "RW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZVBpY2tCb3gQDBIvCitF",
            "bnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlSG9tZVRlbGVwb3J0EA0S",
            "KgomRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZUFkZEJ1ZmYQDhIt",
            "CilFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlUmVtb3ZlQnVmZhAP",
            "EjAKLEVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVQbGF5ZXJSZXNw",
            "YXduEBISOgo2RW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZVBsYXll",
            "clNoYXJlQm90Vmlld1N0YXJ0EBMSOQo1RW50aXR5RXZlbnRUeXBlX0VudGl0",
            "eUV2ZW50VHlwZVBsYXllclNoYXJlQm90Vmlld1N0b3AQFBI0CjBFbnRpdHlF",
            "dmVudFR5cGVfRW50aXR5RXZlbnRUeXBlUzJaUGlja0ZhbGxpbmdCb3gQFRIw",
            "CixFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlUGxheWVyVW5TdHVj",
            "axAXEi8KK0VudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVFbnRlckdv",
            "ZFZpZXcQGBIvCitFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlTGVh",
            "dmVHb2RWaWV3EBkSNQoxRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlw",
            "ZVRlbGVwb3J0QW5kVHJpZ2dlchAaEi4KKkVudGl0eUV2ZW50VHlwZV9FbnRp",
            "dHlFdmVudFR5cGVTdGFydE9yU3RvcBBgEjAKLEVudGl0eUV2ZW50VHlwZV9F",
            "bnRpdHlFdmVudFR5cGVFbnRlcklkZU1vZGVsEGESLworRW50aXR5RXZlbnRU",
            "eXBlX0VudGl0eUV2ZW50VHlwZVF1aXRJZGVNb2RlbBBiEiwKKEVudGl0eUV2",
            "ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVDbGllbnRNc2cQZBIyCi5FbnRpdHlF",
            "dmVudFR5cGVfRW50aXR5RXZlbnRUeXBlSW5wdXRCeUtleXByZXNzEG4SMgou",
            "RW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZUlucHV0QnlTcGVjaWZp",
            "YxBvEioKJkVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVVc2VJdGVt",
            "EHASKwonRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZURyb3BJdGVt",
            "EHESNgoyRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZVBsYXllckR1",
            "bmdlb25VcGRhdGUQchI0CjBFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRU",
            "eXBlUGxheWVySXNzdWVTZXR0bGUQcxIvCitFbnRpdHlFdmVudFR5cGVfRW50",
            "aXR5RXZlbnRUeXBlUGxheWVyVmlld1VwEHQSLworRW50aXR5RXZlbnRUeXBl",
            "X0VudGl0eUV2ZW50VHlwZUNhbWVyYU1vdmVUbxB2EjIKLkVudGl0eUV2ZW50",
            "VHlwZV9FbnRpdHlFdmVudFR5cGVDYW1lcmFTaGFyZVZpZXcQdxIyCi5FbnRp",
            "dHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlUGxheWVyU2hhcmVWaWV3EHgS",
            "MwovRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZUNhbWVyYVR5cGVD",
            "aGFuZ2UQeRIxCi1FbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlQ2Ft",
            "ZXJhUHVsbFZpZXcQehIuCipFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRU",
            "eXBlUmVzZXRQbGF5ZXIQfRI0CjBFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZl",
            "bnRUeXBlUmVzZXRMb2NrZWRFbnRpdHkQfhIzCi5FbnRpdHlFdmVudFR5cGVf",
            "RW50aXR5RXZlbnRUeXBlQ29kZU1vdmVBcnJpdmVkEMgBEjEKLEVudGl0eUV2",
            "ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVDb2RlRXZlbnRDYWxsEM0BEjkKNEVu",
            "dGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVDb2RlT25Db21wb25lbnRP",
            "YmplY3QQ1QESLwoqRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZVBy",
            "b2dyYW1TYXZlENYBEjIKLUVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5",
            "cGVDb2RlU2NyZWVuU2F2ZRDXARIvCipFbnRpdHlFdmVudFR5cGVfRW50aXR5",
            "RXZlbnRUeXBlQ29kZVJlc3RhcnQQ2AESNQowRW50aXR5RXZlbnRUeXBlX0Vu",
            "dGl0eUV2ZW50VHlwZUNvZGVPbkVuZXJneUVtcHR5ENkBEjEKLEVudGl0eUV2",
            "ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVDb2RlT25Db3B5TmV3ENoBEjEKLEVu",
            "dGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVDb2RlT25Db3B5RGVsENsB",
            "EjYKMUVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVDb2RlUXVlc3Rp",
            "b25SZXBsYXkQ3AESOQo0RW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlw",
            "ZUNvZGVFeGVjdXRlU3RhcnRFdmVudBDdARI1CjBFbnRpdHlFdmVudFR5cGVf",
            "RW50aXR5RXZlbnRUeXBlQ29kZVN0b3BDb2RlQmxvY2sQ3gESMQosRW50aXR5",
            "RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZUNvZGVFbnRpdHlBZGQQ4AESNwoy",
            "RW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZUNvZGVPbkVudGl0eU92",
            "ZXJsYXAQ4QESMgotRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZUNv",
            "ZGVPblN0YW1wZWRlEOQBEjUKMEVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVu",
            "dFR5cGVDb2RlT25TdGFtcGVkZUVuZBDlARI2CjFFbnRpdHlFdmVudFR5cGVf",
            "RW50aXR5RXZlbnRUeXBlQ29kZVNldENhblN0YW1wZWRlEOYBEjUKMEVudGl0",
            "eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVDb2RlU2V0Q2FuT3BlcmF0ZRDn",
            "ARIzCi5FbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlQ29kZU9uQnlD",
            "bGlja2VkEO0BEjMKLkVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVD",
            "b2RlT25FbnRlclJvb20Q7gESNgoxRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2",
            "ZW50VHlwZUNvZGVDb3B5RmF0aGVyRGVhZBDvARI0Ci9FbnRpdHlFdmVudFR5",
            "cGVfRW50aXR5RXZlbnRUeXBlQ29kZUVkaXRUaW1lTGluZRDwARI0Ci9FbnRp",
            "dHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlVGltZUxpbmVTaG93VGV4dBDx",
            "ARI1CjBFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlVGltZUxpbmVN",
            "b3ZlVG9Qb3MQ8gESNQowRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlw",
            "ZVRpbWVMaW5lUGxheUF1ZGlvEPMBEjgKM0VudGl0eUV2ZW50VHlwZV9FbnRp",
            "dHlFdmVudFR5cGVUaW1lTGluZVNob3dTdWJ0aXRsZRD0ARIyCi1FbnRpdHlF",
            "dmVudFR5cGVfRW50aXR5RXZlbnRUeXBlQ29kZUNHVmlkZW9FbmQQ9QESNAov",
            "RW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZVF1aWNrQ29kZVJlc3Rh",
            "cnQQ9gESKAojRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZUhpZGUQ",
            "9wESPQo4RW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZUNvZGVFdmVu",
            "dENvZGVOb3RpZmljYXRpb24Q4wISMgotRW50aXR5RXZlbnRUeXBlX0VudGl0",
            "eUV2ZW50VHlwZUNvZGVTZXRQcm9maWxlEOUCEjQKL0VudGl0eUV2ZW50VHlw",
            "ZV9FbnRpdHlFdmVudFR5cGVDb2RlU2V0dGluZ1BhbmVsEOYCEjIKLUVudGl0",
            "eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVDb2RlTWlzc2lvbkVuZBDnAhI2",
            "CjFFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlQ2xpY2tPcGVyYXRl",
            "QnViYmxlEOgCEjQKL0VudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVD",
            "b2RlQ2FtZXJhQWN0aW9uEOkCEjQKL0VudGl0eUV2ZW50VHlwZV9FbnRpdHlF",
            "dmVudFR5cGVQb3BDb21wbGV4RGlnbG9nEOoCEjUKMEVudGl0eUV2ZW50VHlw",
            "ZV9FbnRpdHlFdmVudFR5cGVDb2RlU2V0Q2FycnlDbGFzcxDrAhI1CjBFbnRp",
            "dHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlQm90U2hhcmVWaWV3U3RhcnQQ",
            "kAMSNAovRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZUJvdFNoYXJl",
            "Vmlld1N0b3AQkQMSKwomRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlw",
            "ZUFkZEZ1ZWwQkwMSMQosRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlw",
            "ZUJvdENoYW5nZVNraW4QlAMSLQooRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2",
            "ZW50VHlwZUJvdFJlbmFtZRCVAxIyCi1FbnRpdHlFdmVudFR5cGVfRW50aXR5",
            "RXZlbnRUeXBlQnVpbGRpbmdTd2l0Y2gQwgMSOQo0RW50aXR5RXZlbnRUeXBl",
            "X0VudGl0eUV2ZW50VHlwZUJ1aWxkaW5nTW9kZVBvc1VwZGF0ZRDDAxI2CjFF",
            "bnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlUXVpdEJ1aWxkaW5nU3Rh",
            "dHVzEMQDEjkKNEVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVXb3Jr",
            "YmVuY2hPYmplY3RVcGRhdGUQ9QMSOAozRW50aXR5RXZlbnRUeXBlX0VudGl0",
            "eUV2ZW50VHlwZUJ1aWxkaW5nV2lkZ2V0VXBkYXRlEPYDEjQKL0VudGl0eUV2",
            "ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVXb3JrYmVuY2hBZGRGdWVsEIAEEjYK",
            "MUVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVXb3JrYmVuY2hDb21w",
            "b25lbnQQgQQSOwo2RW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZVdv",
            "cmtiZW5jaFJlc2V0Q29tcG9uZW50EIIEEjYKMUVudGl0eUV2ZW50VHlwZV9F",
            "bnRpdHlFdmVudFR5cGVXb3JrYmVuY2hTZXRQcm9tcHQQgwQSNgoxRW50aXR5",
            "RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZVdvcmtiZW5jaFVwZGF0ZVN1YhCE",
            "BBI5CjRFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlV29ya2JlbmNo",
            "VXBkYXRlRmF0aGVyEIUEEi4KKUVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVu",
            "dFR5cGVFbnRpdHlMb2NrENgEEjAKK0VudGl0eUV2ZW50VHlwZV9FbnRpdHlF",
            "dmVudFR5cGVFbnRpdHlVbkxvY2sQ2QQSOwo2RW50aXR5RXZlbnRUeXBlX0Vu",
            "dGl0eUV2ZW50VHlwZVJlZ2lzdGVyRW50aXR5Q29kZUV2ZW50ENoEEjoKNUVu",
            "dGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVEZXN0cm95RW50aXR5Q29k",
            "ZUV2ZW50ENsEEisKJkVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVC",
            "ZUNsaWNrENwEEjMKLkVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVV",
            "cGRhdGVBbmltYXRpb24Q3QQSLgopRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2",
            "ZW50VHlwZUJlT3BlcmF0ZWQQ3gQSNAovRW50aXR5RXZlbnRUeXBlX0VudGl0",
            "eUV2ZW50VHlwZUVudGl0eUxvY2tVcGRhdGUQ3wQSLwoqRW50aXR5RXZlbnRU",
            "eXBlX0VudGl0eUV2ZW50VHlwZVVwZGF0ZUF1ZGlvEOAEEjUKMEVudGl0eUV2",
            "ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVQbGF5ZXJBZGREaXlBdWRpbxDhBBI1",
            "CjBFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlUGxheWVyR2V0RGl5",
            "QXVkaW8Q4gQSMgotRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZVVw",
            "ZGF0ZVVzZUVtb2ppEOMEEjcKMkVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVu",
            "dFR5cGVBcHBseUVudGl0eVRlbXBsYXRlEOQEEjUKMEVudGl0eUV2ZW50VHlw",
            "ZV9FbnRpdHlFdmVudFR5cGVVcGRhdGVNYXBUZW1wbGF0ZRDlBBI1CjBFbnRp",
            "dHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlTW9uc3RlckxvY2tQbGF5ZXIQ",
            "5gQSOAozRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZVBsYXllckZv",
            "cmNlRXhpdEZpZ2h0EOcEEjIKLUVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVu",
            "dFR5cGVTZW5kTmVhcmJ5Q2hhdBDoBxI+CjlFbnRpdHlFdmVudFR5cGVfRW50",
            "aXR5RXZlbnRUeXBlU2VuZE5lYXJUb0NvZGVFbnRpdHlieUNoYXQQ6QcSKwol",
            "RW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZU51bU1heBD//wMq5gEK",
            "DUV2ZW50Q29kZVR5cGUSJgoiRXZlbnRDb2RlVHlwZV9FdmVudENvZGVUeXBl",
            "VW5rbm93bhAAEiUKIUV2ZW50Q29kZVR5cGVfRXZlbnRDb2RlVHlwZVNlcnZl",
            "chABEioKJkV2ZW50Q29kZVR5cGVfRXZlbnRDb2RlVHlwZUVudGl0eUV2ZW50",
            "EAISLworRXZlbnRDb2RlVHlwZV9FdmVudENvZGVUeXBlUmVjZWl2ZUV2ZW50",
            "Q2FsbBADEikKJUV2ZW50Q29kZVR5cGVfRXZlbnRDb2RlVHlwZUVudGl0eVR5",
            "cGUQBCqHDgoTRW50aXR5Q29kZUV2ZW50VHlwZRIyCi5FbnRpdHlDb2RlRXZl",
            "bnRUeXBlX0VudGl0eUNvZGVFdmVudFR5cGVVbmtub3duEAASNAowRW50aXR5",
            "Q29kZUV2ZW50VHlwZV9FbnRpdHlDb2RlRXZlbnRUeXBlQmVDbGlja2VkEGUS",
            "NAowRW50aXR5Q29kZUV2ZW50VHlwZV9FbnRpdHlDb2RlRXZlbnRUeXBlUG9z",
            "VXBkYXRlEGYSMwovRW50aXR5Q29kZUV2ZW50VHlwZV9FbnRpdHlDb2RlRXZl",
            "bnRUeXBlQmVBdHRhY2sQZxIxCi1FbnRpdHlDb2RlRXZlbnRUeXBlX0VudGl0",
            "eUNvZGVFdmVudFR5cGVBdHRhY2sQaBIvCitFbnRpdHlDb2RlRXZlbnRUeXBl",
            "X0VudGl0eUNvZGVFdmVudFR5cGVEZWFkEGkSMgouRW50aXR5Q29kZUV2ZW50",
            "VHlwZV9FbnRpdHlDb2RlRXZlbnRUeXBlT25Ub3VjaBBqEjYKMkVudGl0eUNv",
            "ZGVFdmVudFR5cGVfRW50aXR5Q29kZUV2ZW50VHlwZUZyYW1lVXBkYXRlEGsS",
            "NQoxRW50aXR5Q29kZUV2ZW50VHlwZV9FbnRpdHlDb2RlRXZlbnRUeXBlRnVl",
            "bFVwZGF0ZRBsEjMKL0VudGl0eUNvZGVFdmVudFR5cGVfRW50aXR5Q29kZUV2",
            "ZW50VHlwZVVzZVNraWxsEG0SNQoxRW50aXR5Q29kZUV2ZW50VHlwZV9FbnRp",
            "dHlDb2RlRXZlbnRUeXBlQ2FuT3BlcmF0ZRBuEjEKLUVudGl0eUNvZGVFdmVu",
            "dFR5cGVfRW50aXR5Q29kZUV2ZW50VHlwZU1pcnJvchBwEjQKMEVudGl0eUNv",
            "ZGVFdmVudFR5cGVfRW50aXR5Q29kZUV2ZW50VHlwZUNvbXBvbmVudBBxEjsK",
            "N0VudGl0eUNvZGVFdmVudFR5cGVfRW50aXR5Q29kZUV2ZW50VHlwZVJlY2Vp",
            "dmVFdmVudENhbGwQchI0CjBFbnRpdHlDb2RlRXZlbnRUeXBlX0VudGl0eUNv",
            "ZGVFdmVudFR5cGVWYXJDaGFuZ2UQcxI7CjdFbnRpdHlDb2RlRXZlbnRUeXBl",
            "X0VudGl0eUNvZGVFdmVudFR5cGVFbnRpdHlCZVN0YW1wZWRlEHQSPwo7RW50",
            "aXR5Q29kZUV2ZW50VHlwZV9FbnRpdHlDb2RlRXZlbnRUeXBlRW50aXR5T3Zl",
            "ckJlU3RhbXBlZGUQdRIyCi5FbnRpdHlDb2RlRXZlbnRUeXBlX0VudGl0eUNv",
            "ZGVFdmVudFR5cGVPbkJ1aWxkEHYSNAowRW50aXR5Q29kZUV2ZW50VHlwZV9F",
            "bnRpdHlDb2RlRXZlbnRUeXBlRW50ZXJSb29tEHcSOQo1RW50aXR5Q29kZUV2",
            "ZW50VHlwZV9FbnRpdHlDb2RlRXZlbnRUeXBlSW5wdXRLZXlBY3Rpb24QeRIz",
            "Ci9FbnRpdHlDb2RlRXZlbnRUeXBlX0VudGl0eUNvZGVFdmVudFR5cGVLZXlw",
            "cmVzcxB6EjIKLkVudGl0eUNvZGVFdmVudFR5cGVfRW50aXR5Q29kZUV2ZW50",
            "VHlwZVVzZUl0ZW0QfBIzCi9FbnRpdHlDb2RlRXZlbnRUeXBlX0VudGl0eUNv",
            "ZGVFdmVudFR5cGVEcm9wSXRlbRB9EjUKMUVudGl0eUNvZGVFdmVudFR5cGVf",
            "RW50aXR5Q29kZUV2ZW50VHlwZVBpY2t1cEl0ZW0QfhIzCi5FbnRpdHlDb2Rl",
            "RXZlbnRUeXBlX0VudGl0eUNvZGVFdmVudFR5cGVPbkNyYXNoEIEBEjoKNUVu",
            "dGl0eUNvZGVFdmVudFR5cGVfRW50aXR5Q29kZUV2ZW50VHlwZURyb3BJdGVt",
            "V2l0aElkEIIBEjYKMUVudGl0eUNvZGVFdmVudFR5cGVfRW50aXR5Q29kZUV2",
            "ZW50VHlwZU9uQ2xvbmVEZWwQgwESNgoxRW50aXR5Q29kZUV2ZW50VHlwZV9F",
            "bnRpdHlFdmVudFR5cGVDb2RlT25CZVBpY2tVcBCHARI3CjJFbnRpdHlDb2Rl",
            "RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZUNvZGVPbkJlUHV0RG93bhCIARI3",
            "CjJFbnRpdHlDb2RlRXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZUNvZGVPbkJl",
            "RGVzdHJveRCJARI9CjhFbnRpdHlDb2RlRXZlbnRUeXBlX0VudGl0eUV2ZW50",
            "VHlwZUNvZGVQbGF5ZXJJc3N1ZVNldHRsZRCKARJCCj1FbnRpdHlDb2RlRXZl",
            "bnRUeXBlX0VudGl0eUV2ZW50VHlwZUVudGl0aWVzUXVpY2tDb2RlUnVuT3JT",
            "dG9wEIsBKloKDERhdGFTYXZlVHlwZRIkCiBEYXRhU2F2ZVR5cGVfRGF0YVNh",
            "dmVUeXBlVW5rbm93bhAAEiQKH0RhdGFTYXZlVHlwZV9EYXRhU2F2ZVR5cGVN",
            "YXBHb2IQ6QcqpAIKFFNjZW5lRm9yY2VSZW1vdmVUaW1lEjQKMFNjZW5lRm9y",
            "Y2VSZW1vdmVUaW1lX1NjZW5lRm9yY2VSZW1vdmVUaW1lVW5rbm93bhAAEjMK",
            "LlNjZW5lRm9yY2VSZW1vdmVUaW1lX1NjZW5lRm9yY2VSZW1vdmVUaW1lTGVh",
            "dmUQ0Q8SNgoxU2NlbmVGb3JjZVJlbW92ZVRpbWVfU2NlbmVGb3JjZVJlbW92",
            "ZVRpbWVUYXJnZXRSQxDSDxI1CjBTY2VuZUZvcmNlUmVtb3ZlVGltZV9TY2Vu",
            "ZUZvcmNlUmVtb3ZlVGltZVJ1blRpbWUQ0w8SMgotU2NlbmVGb3JjZVJlbW92",
            "ZVRpbWVfU2NlbmVGb3JjZVJlbW92ZVRpbWVEaXN0ENQPYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MelandGame3.ServerMsgEventType), typeof(global::MelandGame3.ServerEventType), typeof(global::MelandGame3.WorldEventType), typeof(global::MelandGame3.GridEventType), typeof(global::MelandGame3.EntityEventType), typeof(global::MelandGame3.EventCodeType), typeof(global::MelandGame3.EntityCodeEventType), typeof(global::MelandGame3.DataSaveType), typeof(global::MelandGame3.SceneForceRemoveTime), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ServerMsgEventType {
    /// <summary>
    /// 未知类型
    /// </summary>
    [pbr::OriginalName("ServerMsgEventType_ServerMsgEventTypeUnknow")] ServerMsgEventTypeUnknow = 0,
    /// <summary>
    /// 收到消息
    /// </summary>
    [pbr::OriginalName("ServerMsgEventType_ServerMsgEventTypeReceiveMsg")] ServerMsgEventTypeReceiveMsg = 1,
    /// <summary>
    /// 触发回调
    /// </summary>
    [pbr::OriginalName("ServerMsgEventType_ServerMsgEventTypeCallBack")] ServerMsgEventTypeCallBack = 2,
    /// <summary>
    /// 消息超时
    /// </summary>
    [pbr::OriginalName("ServerMsgEventType_ServerMsgEventTypeTimeOut")] ServerMsgEventTypeTimeOut = 3,
  }

  public enum ServerEventType {
    [pbr::OriginalName("ServerEventType_ServerEventTypeServerUnknown")] ServerEventTypeServerUnknown = 0,
    /// <summary>
    /// 服务器驱动事件 10-99
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeServerAfterConfig")] ServerEventTypeServerAfterConfig = 10,
    [pbr::OriginalName("ServerEventType_ServerEventTypeServerMinutely")] ServerEventTypeServerMinutely = 11,
    [pbr::OriginalName("ServerEventType_ServerEventTypeServerHourly")] ServerEventTypeServerHourly = 12,
    [pbr::OriginalName("ServerEventType_ServerEventTypeServerDaily")] ServerEventTypeServerDaily = 13,
    [pbr::OriginalName("ServerEventType_ServerEventTypeServerConnClose")] ServerEventTypeServerConnClose = 14,
    [pbr::OriginalName("ServerEventType_ServerEventTypeServerConnConnect")] ServerEventTypeServerConnConnect = 15,
    [pbr::OriginalName("ServerEventType_ServerEventTypeServerTimer")] ServerEventTypeServerTimer = 16,
    [pbr::OriginalName("ServerEventType_ServerEventTypeSqlRollBack")] ServerEventTypeSqlRollBack = 17,
    [pbr::OriginalName("ServerEventType_ServerEventTypeServerEventCall")] ServerEventTypeServerEventCall = 18,
    /// <summary>
    /// -------------------------------------------------------------------------
    /// 角色事件 100-199
    /// -------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerCreated")] ServerEventTypePlayerCreated = 100,
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerOnline")] ServerEventTypePlayerOnline = 101,
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerOffline")] ServerEventTypePlayerOffline = 102,
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerNewDay")] ServerEventTypePlayerNewDay = 103,
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerLvUp")] ServerEventTypePlayerLvUp = 104,
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerResetProfile")] ServerEventTypePlayerResetProfile = 105,
    /// <summary>
    /// 技能更新
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerUpdateSkill")] ServerEventTypePlayerUpdateSkill = 106,
    /// <summary>
    /// exp增加
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerAddExp")] ServerEventTypePlayerAddExp = 107,
    /// <summary>
    /// HP回复
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerReplyHp")] ServerEventTypePlayerReplyHp = 108,
    /// <summary>
    ///解锁配方
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeUnlockFormula")] ServerEventTypeUnlockFormula = 109,
    [pbr::OriginalName("ServerEventType_ServerEventTypeCalculatePlayerProfile")] ServerEventTypeCalculatePlayerProfile = 110,
    /// <summary>
    /// 玩家使用技能
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerUseSkill")] ServerEventTypePlayerUseSkill = 111,
    /// <summary>
    /// 玩家被攻击
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerBeAttack")] ServerEventTypePlayerBeAttack = 112,
    /// <summary>
    /// 销毁item
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeDestoryItem")] ServerEventTypeDestoryItem = 114,
    /// <summary>
    /// 销毁所有item
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeDestoryAllItem")] ServerEventTypeDestoryAllItem = 115,
    /// <summary>
    /// 添加item
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeAddItem")] ServerEventTypeAddItem = 116,
    /// <summary>
    /// 玩家兑换cdkey
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeRedeemCDKey")] ServerEventTypeRedeemCdkey = 117,
    /// <summary>
    /// 玩家神庙等级升级
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeDungeon")] ServerEventTypeDungeon = 118,
    /// <summary>
    /// send chat message
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeSendChatMsg")] ServerEventTypeSendChatMsg = 119,
    [pbr::OriginalName("ServerEventType_ServerEventTypeSendUpdateChatState")] ServerEventTypeSendUpdateChatState = 120,
    [pbr::OriginalName("ServerEventType_ServerEventTypeSendRemoveChatMsg")] ServerEventTypeSendRemoveChatMsg = 121,
    /// <summary>
    /// -------------------------------------------------------------------------
    /// 来自场景的通知 200-1000
    /// -------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventZoneSendToPlayer")] ServerEventZoneSendToPlayer = 200,
    [pbr::OriginalName("ServerEventType_Z2SZoneBroadcast")] Z2SzoneBroadcast = 202,
    [pbr::OriginalName("ServerEventType_ServerEventEntityAnimationCreate")] ServerEventEntityAnimationCreate = 203,
    [pbr::OriginalName("ServerEventType_ServerEventEntityAnimationUpdate")] ServerEventEntityAnimationUpdate = 204,
    [pbr::OriginalName("ServerEventType_ServerEventEntityAnimationDel")] ServerEventEntityAnimationDel = 205,
    [pbr::OriginalName("ServerEventType_Z2SGobMapSave")] Z2SgobMapSave = 206,
    [pbr::OriginalName("ServerEventType_ServerEventEntityPlayerUpdate")] ServerEventEntityPlayerUpdate = 207,
    [pbr::OriginalName("ServerEventType_Z2SEntityTemplateSave")] Z2SentityTemplateSave = 208,
    [pbr::OriginalName("ServerEventType_Z2SPlayerOffline")] Z2SplayerOffline = 210,
    [pbr::OriginalName("ServerEventType_Z2SPlayerManorData")] Z2SplayerManorData = 211,
    /// <summary>
    ///保存实体
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventEntitySave")] ServerEventEntitySave = 213,
    /// <summary>
    /// 建造
    /// </summary>
    [pbr::OriginalName("ServerEventType_Z2SBuildDelete")] Z2SbuildDelete = 242,
    [pbr::OriginalName("ServerEventType_ServerEventBuild")] ServerEventBuild = 243,
    [pbr::OriginalName("ServerEventType_Z2SPuppetDelete")] Z2SpuppetDelete = 244,
    /// <summary>
    ///数据落地
    /// </summary>
    [pbr::OriginalName("ServerEventType_Z2SPlayerSave")] Z2SplayerSave = 399,
    [pbr::OriginalName("ServerEventType_Z2SEntitySave")] Z2SentitySave = 400,
    [pbr::OriginalName("ServerEventType_Z2SManorPacket")] Z2SmanorPacket = 401,
    /// <summary>
    /// 代码块 500-700
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventCodeExecute")] ServerEventCodeExecute = 500,
    [pbr::OriginalName("ServerEventType_ServerEventUseItemFromZone")] ServerEventUseItemFromZone = 501,
    [pbr::OriginalName("ServerEventType_ServerEventDropItemFromZone")] ServerEventDropItemFromZone = 502,
    [pbr::OriginalName("ServerEventType_ServerEventBotBuildFromZone")] ServerEventBotBuildFromZone = 503,
    [pbr::OriginalName("ServerEventType_ServerEventMakeItemFromZone")] ServerEventMakeItemFromZone = 505,
    [pbr::OriginalName("ServerEventType_ServerEventTakeWorkbenchItemByCidFromZone")] ServerEventTakeWorkbenchItemByCidFromZone = 506,
    [pbr::OriginalName("ServerEventType_ServerEventGiveWorkbenchItemByCidFromZone")] ServerEventGiveWorkbenchItemByCidFromZone = 507,
    [pbr::OriginalName("ServerEventType_ServerEventPlayerCompleteChapter")] ServerEventPlayerCompleteChapter = 508,
    [pbr::OriginalName("ServerEventType_ServerEventMissionEnter")] ServerEventMissionEnter = 509,
    [pbr::OriginalName("ServerEventType_ServerEventAcceptTask")] ServerEventAcceptTask = 510,
    [pbr::OriginalName("ServerEventType_ServerEventSubmitTask")] ServerEventSubmitTask = 511,
    [pbr::OriginalName("ServerEventType_ServerEventComplateTask")] ServerEventComplateTask = 512,
    [pbr::OriginalName("ServerEventType_ServerEventMissionEnterSceneMonitor")] ServerEventMissionEnterSceneMonitor = 513,
    /// <summary>
    /// 战斗
    ///ServerEventType_Z2S_PickItem = 711;
    /// </summary>
    [pbr::OriginalName("ServerEventType_Z2S_PlayerDead")] Z2SPlayerDead = 712,
    [pbr::OriginalName("ServerEventType_ServerEventZ2SAddExpToBot")] ServerEventZ2SaddExpToBot = 715,
    /// <summary>
    /// 机器人
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventZ2SBotDead")] ServerEventZ2SbotDead = 731,
    /// <summary>
    /// 工作台
    /// </summary>
    [pbr::OriginalName("ServerEventType_Z2SPlantDelete")] Z2SplantDelete = 753,
    [pbr::OriginalName("ServerEventType_Z2SPetDelete")] Z2SpetDelete = 754,
    /// <summary>
    /// -------------------------------------------------------------------------
    /// (机器人)事件 800-899
    /// -------------------------------------------------------------------------
    /// (机器人)更换装备
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeBotCreated")] ServerEventTypeBotCreated = 800,
    /// <summary>
    /// (机器人)升级
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeBotLvUp")] ServerEventTypeBotLvUp = 801,
    /// <summary>
    /// (机器人)更换装备
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeUpdateBotEquipment")] ServerEventTypeUpdateBotEquipment = 802,
    /// <summary>
    /// exp增加
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeBotAddExp")] ServerEventTypeBotAddExp = 803,
    /// <summary>
    /// HP回复
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeBotReplyHp")] ServerEventTypeBotReplyHp = 804,
    /// <summary>
    /// bot背包添加物品
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeBotAddObject")] ServerEventTypeBotAddObject = 805,
    /// <summary>
    /// 召回机器人
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeRecallBot")] ServerEventTypeRecallBot = 806,
    /// <summary>
    /// 机器人使用技能
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeBotUseSkill")] ServerEventTypeBotUseSkill = 807,
    /// <summary>
    /// 玩家被攻击
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeBotBeAttack")] ServerEventTypeBotBeAttack = 808,
    /// <summary>
    /// 添加物品（带属性的）
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeBotAddItem")] ServerEventTypeBotAddItem = 809,
    /// <summary>
    /// -------------------------------------------------------------------------
    /// 背包event协议号 900 - 999
    /// -------------------------------------------------------------------------
    /// 使用消耗品
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerUseConsumable")] ServerEventTypePlayerUseConsumable = 902,
    /// <summary>
    /// 添加物品
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerAddObject")] ServerEventTypePlayerAddObject = 903,
    /// <summary>
    /// 拾取物品
    /// </summary>
    [pbr::OriginalName("ServerEventType_Z2SPickFalling")] Z2SpickFalling = 904,
    /// <summary>
    /// 拾取包裹
    /// </summary>
    [pbr::OriginalName("ServerEventType_Z2SPickFallingBox")] Z2SpickFallingBox = 905,
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerUseObject")] ServerEventTypePlayerUseObject = 907,
    [pbr::OriginalName("ServerEventType_ServerEventTypeAddItemByOperateBubble")] ServerEventTypeAddItemByOperateBubble = 908,
    [pbr::OriginalName("ServerEventType_ServerEventTypeTakeItemByOperateBubble")] ServerEventTypeTakeItemByOperateBubble = 909,
    [pbr::OriginalName("ServerEventType_ServerEventTypeReplaceItemByOperateBubble")] ServerEventTypeReplaceItemByOperateBubble = 910,
    /// <summary>
    /// 重置玩家nft道具的使用状态
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeResetPlayerNftStatus")] ServerEventTypeResetPlayerNftStatus = 911,
    [pbr::OriginalName("ServerEventType_ServerEventTypeUpdatePlayerNFTs")] ServerEventTypeUpdatePlayerNfts = 912,
    /// <summary>
    /// 更新第三方nft道具的过期时间
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeUpdateThirdNftTimeOut")] ServerEventTypeUpdateThirdNftTimeOut = 915,
    /// <summary>
    /// -------------------------------------------------------------------------
    /// 任务系统 1000-1050
    /// -------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerAcceptedTask")] ServerEventTypePlayerAcceptedTask = 1001,
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerSubmittedTask")] ServerEventTypePlayerSubmittedTask = 1002,
    [pbr::OriginalName("ServerEventType_ServerEventTypeUpdateNpcTaskNoticeType")] ServerEventTypeUpdateNpcTaskNoticeType = 1003,
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerTaskStateUpdate")] ServerEventTypePlayerTaskStateUpdate = 1005,
    /// <summary>
    /// 任务
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTaskProgressChange")] ServerEventTaskProgressChange = 1049,
    /// <summary>
    /// -------------------------------------------------------------------------
    /// 邮件event协议号 1050 - 1100
    /// -------------------------------------------------------------------------
    /// 添加个人邮件
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerAddMail")] ServerEventTypePlayerAddMail = 1051,
    /// <summary>
    /// 添加全服邮件
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeServerSendMailByTemplateId")] ServerEventTypeServerSendMailByTemplateId = 1052,
    /// <summary>
    /// -------------------------------------------------------------------------
    /// 大世界event协议号 9000 - 10000
    /// -------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeLandGroupCreate")] ServerEventTypeLandGroupCreate = 9000,
    [pbr::OriginalName("ServerEventType_ServerEventTypeLandGroupUpdate")] ServerEventTypeLandGroupUpdate = 9001,
    [pbr::OriginalName("ServerEventType_ServerEventTypeLandGroupRemove")] ServerEventTypeLandGroupRemove = 9002,
    /// <summary>
    /// -------------------------------------------------------------------------
    /// 最大事件数
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeNumMax")] ServerEventTypeNumMax = 65535,
  }

  public enum WorldEventType {
    /// <summary>
    /// 场景事件
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeUnknown")] WorldEventTypeUnknown = 0,
    [pbr::OriginalName("WorldEventType_WorldEventTypeSendToZone")] WorldEventTypeSendToZone = 1,
    [pbr::OriginalName("WorldEventType_WorldEventTypeEnterMap")] WorldEventTypeEnterMap = 2,
    [pbr::OriginalName("WorldEventType_WorldEventTypeLeaveMap")] WorldEventTypeLeaveMap = 3,
    [pbr::OriginalName("WorldEventType_WorldEventTypeMove")] WorldEventTypeMove = 4,
    [pbr::OriginalName("WorldEventType_WorldEventTypeMapSave")] WorldEventTypeMapSave = 5,
    [pbr::OriginalName("WorldEventType_WorldEventTypeReloadResourcePoint")] WorldEventTypeReloadResourcePoint = 6,
    [pbr::OriginalName("WorldEventType_WorldEventTypeInitMapElement")] WorldEventTypeInitMapElement = 7,
    [pbr::OriginalName("WorldEventType_WorldEventTypeEntitySave")] WorldEventTypeEntitySave = 8,
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerReset")] WorldEventTypePlayerReset = 9,
    [pbr::OriginalName("WorldEventType_WorldEventTypeResetAreaState")] WorldEventTypeResetAreaState = 10,
    /// <summary>
    /// 环境
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeDiurnalCycleChange")] WorldEventTypeDiurnalCycleChange = 30,
    /// <summary>
    /// chunk事件
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeEntityEventCall")] WorldEventTypeEntityEventCall = 101,
    [pbr::OriginalName("WorldEventType_WorldEventTypeAddEntityToChunkGrid")] WorldEventTypeAddEntityToChunkGrid = 102,
    [pbr::OriginalName("WorldEventType_WorldEventTypeGetEntity")] WorldEventTypeGetEntity = 104,
    [pbr::OriginalName("WorldEventType_WorldEventTypeEntityEventCallNoReturn")] WorldEventTypeEntityEventCallNoReturn = 105,
    [pbr::OriginalName("WorldEventType_WorldEventTypeRestartAllEntitiesCodeBlock")] WorldEventTypeRestartAllEntitiesCodeBlock = 106,
    [pbr::OriginalName("WorldEventType_WorldEventTypeResourceLoadFinish")] WorldEventTypeResourceLoadFinish = 107,
    [pbr::OriginalName("WorldEventType_WorldEventTypeUpdateWidgetAttr")] WorldEventTypeUpdateWidgetAttr = 108,
    /// <summary>
    ///领地物件运行代码块事件
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeRunCodeBlockByPlayerArea")] WorldEventTypeRunCodeBlockByPlayerArea = 109,
    [pbr::OriginalName("WorldEventType_WorldEventTypeEntitiesRestartCodeBlock")] WorldEventTypeEntitiesRestartCodeBlock = 110,
    /// <summary>
    ///公共领地所有实体重启代码块
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypePublicAreaRestartCode")] WorldEventTypePublicAreaRestartCode = 112,
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerAreaRestartCode")] WorldEventTypePlayerAreaRestartCode = 113,
    [pbr::OriginalName("WorldEventType_WorldEventTypeRemoveEntityChange")] WorldEventTypeRemoveEntityChange = 114,
    [pbr::OriginalName("WorldEventType_WorldEventTypeReviveEntity")] WorldEventTypeReviveEntity = 115,
    /// <summary>
    ///副本地图回溯 事件
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeRestartDungeonMap")] WorldEventTypeRestartDungeonMap = 116,
    /// <summary>
    ///  触发实体的开始事件代码块
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeEntitiesExecuteStartEvent")] WorldEventTypeEntitiesExecuteStartEvent = 117,
    /// <summary>
    /// 停止实体的所有代码块(重置到事件等待触发状态)
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeEntitiesStopCodeBlock")] WorldEventTypeEntitiesStopCodeBlock = 118,
    /// <summary>
    /// 应用组件模板到实体
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeApplyEntityTemplate")] WorldEventTypeApplyEntityTemplate = 120,
    [pbr::OriginalName("WorldEventType_WorldEventTypeAddCameraToChunkGrid")] WorldEventTypeAddCameraToChunkGrid = 121,
    /// <summary>
    /// 场景区域重新运行代码块
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeZoneAreaRestartCode")] WorldEventTypeZoneAreaRestartCode = 122,
    [pbr::OriginalName("WorldEventType_WorldEventTypeAddEntityWithoutViewToChunkGrid")] WorldEventTypeAddEntityWithoutViewToChunkGrid = 123,
    [pbr::OriginalName("WorldEventType_WorldEventTypeCodeEventNotification")] WorldEventTypeCodeEventNotification = 124,
    [pbr::OriginalName("WorldEventType_WorldEventTypePublicAreaResetCodeBlock")] WorldEventTypePublicAreaResetCodeBlock = 125,
    /// <summary>
    /// 场景区域运行开始代码块
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeEntitiesExecuteQuickCodeStartEvent")] WorldEventTypeEntitiesExecuteQuickCodeStartEvent = 126,
    /// <summary>
    /// 运行或停止区域中可编码实体的快速编码状态
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeResetEntitiesQuickCodeState")] WorldEventTypeResetEntitiesQuickCodeState = 127,
    /// <summary>
    /// 区域所有多实体快速编码标签页信息
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeEntitiesQuickCodeTabDatas")] WorldEventTypeEntitiesQuickCodeTabDatas = 128,
    /// <summary>
    /// grid 事件
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeToGridEvent")] WorldEventTypeToGridEvent = 150,
    [pbr::OriginalName("WorldEventType_WorldEventTypeZoomEvent")] WorldEventTypeZoomEvent = 151,
    /// <summary>
    /// build
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerAddEntity")] WorldEventTypePlayerAddEntity = 201,
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerDelEntity")] WorldEventTypePlayerDelEntity = 202,
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerMoveEntity")] WorldEventTypePlayerMoveEntity = 203,
    [pbr::OriginalName("WorldEventType_WorldEventTypeBotAddEntity")] WorldEventTypeBotAddEntity = 204,
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerDelEntityByScene")] WorldEventTypePlayerDelEntityByScene = 205,
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerAddResourcePoint")] WorldEventTypePlayerAddResourcePoint = 210,
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerDelResourcePoint")] WorldEventTypePlayerDelResourcePoint = 211,
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerAddBornPoint")] WorldEventTypePlayerAddBornPoint = 212,
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerDelBornPoint")] WorldEventTypePlayerDelBornPoint = 213,
    /// <summary>
    ///s2z
    /// </summary>
    [pbr::OriginalName("WorldEventType_S2ZLessonAreaCreate")] S2ZlessonAreaCreate = 214,
    [pbr::OriginalName("WorldEventType_S2ZLessonAreaDel")] S2ZlessonAreaDel = 215,
    [pbr::OriginalName("WorldEventType_S2ZLessonAreaQuery")] S2ZlessonAreaQuery = 216,
    [pbr::OriginalName("WorldEventType_S2ZLessonAreaUpdate")] S2ZlessonAreaUpdate = 217,
    [pbr::OriginalName("WorldEventType_S2ZBeautyAreaUpdate")] S2ZbeautyAreaUpdate = 218,
    [pbr::OriginalName("WorldEventType_S2ZLessonAreaCopy")] S2ZlessonAreaCopy = 219,
    [pbr::OriginalName("WorldEventType_S2ZLessonAreaIndexUpdate")] S2ZlessonAreaIndexUpdate = 220,
    [pbr::OriginalName("WorldEventType_S2ZLessonAreaUnlock")] S2ZlessonAreaUnlock = 221,
    [pbr::OriginalName("WorldEventType_S2ZLessonPlayerArrivedArea")] S2ZlessonPlayerArrivedArea = 222,
    [pbr::OriginalName("WorldEventType_S2ZLessonAreaRunQuickCodeStart")] S2ZlessonAreaRunQuickCodeStart = 223,
    [pbr::OriginalName("WorldEventType_WorldEventTypeAddTileMapSign")] WorldEventTypeAddTileMapSign = 224,
    [pbr::OriginalName("WorldEventType_WorldEventTypeRemoveTileMapSign")] WorldEventTypeRemoveTileMapSign = 225,
    /// <summary>
    /// bot
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeSpawnBot")] WorldEventTypeSpawnBot = 301,
    [pbr::OriginalName("WorldEventType_WorldEventTypeRecallBot")] WorldEventTypeRecallBot = 302,
    /// <summary>
    /// 功能实体事件
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeIssueSettle")] WorldEventTypeIssueSettle = 401,
    [pbr::OriginalName("WorldEventType_WorldEventTypeGetEntityIssue")] WorldEventTypeGetEntityIssue = 402,
    /// <summary>
    ///工作台事件
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeWorkbenchUpdateSub")] WorldEventTypeWorkbenchUpdateSub = 506,
    [pbr::OriginalName("WorldEventType_WorldEventTypeWorkbenchUpdateFather")] WorldEventTypeWorkbenchUpdateFather = 507,
    /// <summary>
    /// 玩家领地
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeSpawnPalyerArea")] WorldEventTypeSpawnPalyerArea = 600,
    [pbr::OriginalName("WorldEventType_WorldEventTypeMovePalyerArea")] WorldEventTypeMovePalyerArea = 601,
    [pbr::OriginalName("WorldEventType_WorldEventTypeRemovePalyerArea")] WorldEventTypeRemovePalyerArea = 602,
    [pbr::OriginalName("WorldEventType_WorldEventTypeQueryMyPalyerArea")] WorldEventTypeQueryMyPalyerArea = 603,
    [pbr::OriginalName("WorldEventType_WorldEventTypeSetGlobalVar")] WorldEventTypeSetGlobalVar = 604,
    [pbr::OriginalName("WorldEventType_WorldEventTypeQueryPalyerAreas")] WorldEventTypeQueryPalyerAreas = 605,
    [pbr::OriginalName("WorldEventType_WorldEventTypeQueryPalyerAreaByRc")] WorldEventTypeQueryPalyerAreaByRc = 606,
    [pbr::OriginalName("WorldEventType_S2ZManorBuy")] S2ZmanorBuy = 610,
    [pbr::OriginalName("WorldEventType_S2ZManorBuyMarkSync")] S2ZmanorBuyMarkSync = 611,
    /// <summary>
    ///领地打包成模板
    /// </summary>
    [pbr::OriginalName("WorldEventType_S2ZManorTemplatePacket")] S2ZmanorTemplatePacket = 612,
    /// <summary>
    ///应用领地模
    /// </summary>
    [pbr::OriginalName("WorldEventType_S2ZManorTemplateUse")] S2ZmanorTemplateUse = 613,
    /// <summary>
    /// B端 老师重置公共领地
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeTeacherResetPublicManor")] WorldEventTypeTeacherResetPublicManor = 614,
    /// <summary>
    /// 领取空领地
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeCreatAreaByEmptyArea")] WorldEventTypeCreatAreaByEmptyArea = 615,
    /// <summary>
    /// 检测领地
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeManorTemplateCheck")] WorldEventTypeManorTemplateCheck = 616,
    /// <summary>
    /// 广播
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeAreaUpdateTemplate")] WorldEventTypeAreaUpdateTemplate = 617,
    /// <summary>
    /// 将地图数据加载到领地中
    /// </summary>
    [pbr::OriginalName("WorldEventType_S2ZPlayerAreaLoadManorMap")] S2ZplayerAreaLoadManorMap = 618,
    /// <summary>
    ///领地改变大小
    /// </summary>
    [pbr::OriginalName("WorldEventType_S2ZManorTemplateChangeSize")] S2ZmanorTemplateChangeSize = 619,
    /// <summary>
    /// 领地回收
    /// </summary>
    [pbr::OriginalName("WorldEventType_S2ZPlayerManorTakeBack")] S2ZplayerManorTakeBack = 620,
    /// <summary>
    /// 更新领地回收时间
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeUpdateAreaRecoverTime")] WorldEventTypeUpdateAreaRecoverTime = 621,
    /// <summary>
    /// 撤销重做
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeUndo")] WorldEventTypeUndo = 701,
    /// <summary>
    /// 重做
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeRedo")] WorldEventTypeRedo = 702,
    /// <summary>
    ///--------------代码块事件   800 ~ 899   -----------------
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeCodeblockAddEntity")] WorldEventTypeCodeblockAddEntity = 801,
    [pbr::OriginalName("WorldEventType_WorldEventTypeCodeblockDelEntity")] WorldEventTypeCodeblockDelEntity = 802,
    /// <summary>
    ///透传过来的客户端消息
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeClientMsg")] WorldEventTypeClientMsg = 9801,
    /// <summary>
    /// gm 9901~9999
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeGmAddEntity")] WorldEventTypeGmAddEntity = 9901,
    /// <summary>
    /// -------------------------------------------------------------------------
    /// 大世界event协议号 9000 - 10000
    /// -------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerAddBigWorldSystemArea")] WorldEventTypePlayerAddBigWorldSystemArea = 9000,
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerDelBigWorldSystemArea")] WorldEventTypePlayerDelBigWorldSystemArea = 9001,
    /// <summary>
    /// 最大事件数
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeNumMax")] WorldEventTypeNumMax = 65535,
  }

  public enum GridEventType {
    /// <summary>
    /// 场景事件
    /// </summary>
    [pbr::OriginalName("GridEventType_GridEventTypeUnknown")] GridEventTypeUnknown = 0,
    [pbr::OriginalName("GridEventType_GridEventTypeEntityEvent")] GridEventTypeEntityEvent = 1,
  }

  public enum EntityEventType {
    /// <summary>
    /// 场景事件
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeUnknown")] EntityEventTypeUnknown = 0,
    /// <summary>
    /// --------------- 玩家事件 ----------------------------
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeMoveTo")] EntityEventTypeMoveTo = 1,
    [pbr::OriginalName("EntityEventType_EntityEventTypeUseSkill")] EntityEventTypeUseSkill = 2,
    /// <summary>
    /// 换装
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeChangeAvatars")] EntityEventTypeChangeAvatars = 3,
    /// <summary>
    /// 玩家属性更新
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeUpdateProfile")] EntityEventTypeUpdateProfile = 4,
    /// <summary>
    /// 玩家技能更新(skillId=0->当前没有技能)
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeUpdateSkill")] EntityEventTypeUpdateSkill = 5,
    /// <summary>
    /// 玩家等级更新
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeUpdateLevel")] EntityEventTypeUpdateLevel = 6,
    /// <summary>
    /// 玩家恢复hp(快速)
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeRecoveryHp")] EntityEventTypeRecoveryHp = 7,
    /// <summary>
    /// 传送
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeTeleport")] EntityEventTypeTeleport = 9,
    /// <summary>
    /// 拾取掉落物品
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypePickFalling")] EntityEventTypePickFalling = 11,
    /// <summary>
    /// 拾取掉落包裹(FallingBox)
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypePickBox")] EntityEventTypePickBox = 12,
    /// <summary>
    ///传送回家
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeHomeTeleport")] EntityEventTypeHomeTeleport = 13,
    /// <summary>
    ///添加buff
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeAddBuff")] EntityEventTypeAddBuff = 14,
    /// <summary>
    ///删除buff
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeRemoveBuff")] EntityEventTypeRemoveBuff = 15,
    /// <summary>
    ///角色复活(客户端消息)
    ///EntityEventType_EntityEventTypeC2ZPlayerRelive = 17;
    ///角色复活(逻辑层检测完复活区域后发送给场景层)
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerRespawn")] EntityEventTypePlayerRespawn = 18,
    /// <summary>
    ///通知玩家开始共享机器人视野
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerShareBotViewStart")] EntityEventTypePlayerShareBotViewStart = 19,
    /// <summary>
    ///通知玩家停止共享机器人视野
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerShareBotViewStop")] EntityEventTypePlayerShareBotViewStop = 20,
    /// <summary>
    ///拾取包裹返回
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeS2ZPickFallingBox")] EntityEventTypeS2ZpickFallingBox = 21,
    /// <summary>
    ///一键解卡
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerUnStuck")] EntityEventTypePlayerUnStuck = 23,
    /// <summary>
    ///进入上帝视角
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeEnterGodView")] EntityEventTypeEnterGodView = 24,
    /// <summary>
    ///离开上帝视角
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeLeaveGodView")] EntityEventTypeLeaveGodView = 25,
    /// <summary>
    ///tp实体并触发事件
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeTeleportAndTrigger")] EntityEventTypeTeleportAndTrigger = 26,
    [pbr::OriginalName("EntityEventType_EntityEventTypeStartOrStop")] EntityEventTypeStartOrStop = 96,
    [pbr::OriginalName("EntityEventType_EntityEventTypeEnterIdeModel")] EntityEventTypeEnterIdeModel = 97,
    [pbr::OriginalName("EntityEventType_EntityEventTypeQuitIdeModel")] EntityEventTypeQuitIdeModel = 98,
    [pbr::OriginalName("EntityEventType_EntityEventTypeClientMsg")] EntityEventTypeClientMsg = 100,
    /// <summary>
    /// 按键输入事件
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeInputByKeypress")] EntityEventTypeInputByKeypress = 110,
    /// <summary>
    /// 其他输入事件
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeInputBySpecific")] EntityEventTypeInputBySpecific = 111,
    /// <summary>
    /// 实体使用物件
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeUseItem")] EntityEventTypeUseItem = 112,
    /// <summary>
    /// 实体丢弃物件
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeDropItem")] EntityEventTypeDropItem = 113,
    /// <summary>
    /// 更新玩家副本闯关信息
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerDungeonUpdate")] EntityEventTypePlayerDungeonUpdate = 114,
    /// <summary>
    /// 玩家完成答题（添加积分和执行后续代码块）
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerIssueSettle")] EntityEventTypePlayerIssueSettle = 115,
    /// <summary>
    /// 更新玩家视野
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerViewUp")] EntityEventTypePlayerViewUp = 116,
    /// <summary>
    /// 玩家镜头移动
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeCameraMoveTo")] EntityEventTypeCameraMoveTo = 118,
    /// <summary>
    ///通知镜头是否使用摄像头视野
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeCameraShareView")] EntityEventTypeCameraShareView = 119,
    /// <summary>
    ///通知玩家是否使用镜头视野
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerShareView")] EntityEventTypePlayerShareView = 120,
    /// <summary>
    ///客户端预览镜头
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeCameraTypeChange")] EntityEventTypeCameraTypeChange = 121,
    /// <summary>
    ///预览镜头拉取视野
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeCameraPullView")] EntityEventTypeCameraPullView = 122,
    /// <summary>
    /// 重置玩家
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeResetPlayer")] EntityEventTypeResetPlayer = 125,
    /// <summary>
    /// 重置玩家实体锁定状态
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeResetLockedEntity")] EntityEventTypeResetLockedEntity = 126,
    /// <summary>
    /// --------------- 代码块 200-399 ------------------------
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeMoveArrived")] EntityEventTypeCodeMoveArrived = 200,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeEventCall")] EntityEventTypeCodeEventCall = 205,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeOnComponentObject")] EntityEventTypeCodeOnComponentObject = 213,
    [pbr::OriginalName("EntityEventType_EntityEventTypeProgramSave")] EntityEventTypeProgramSave = 214,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeScreenSave")] EntityEventTypeCodeScreenSave = 215,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeRestart")] EntityEventTypeCodeRestart = 216,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeOnEnergyEmpty")] EntityEventTypeCodeOnEnergyEmpty = 217,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeOnCopyNew")] EntityEventTypeCodeOnCopyNew = 218,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeOnCopyDel")] EntityEventTypeCodeOnCopyDel = 219,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeQuestionReplay")] EntityEventTypeCodeQuestionReplay = 220,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeExecuteStartEvent")] EntityEventTypeCodeExecuteStartEvent = 221,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeStopCodeBlock")] EntityEventTypeCodeStopCodeBlock = 222,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeEntityAdd")] EntityEventTypeCodeEntityAdd = 224,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeOnEntityOverlap")] EntityEventTypeCodeOnEntityOverlap = 225,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeOnStampede")] EntityEventTypeCodeOnStampede = 228,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeOnStampedeEnd")] EntityEventTypeCodeOnStampedeEnd = 229,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeSetCanStampede")] EntityEventTypeCodeSetCanStampede = 230,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeSetCanOperate")] EntityEventTypeCodeSetCanOperate = 231,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeOnByClicked")] EntityEventTypeCodeOnByClicked = 237,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeOnEnterRoom")] EntityEventTypeCodeOnEnterRoom = 238,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeCopyFatherDead")] EntityEventTypeCodeCopyFatherDead = 239,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeEditTimeLine")] EntityEventTypeCodeEditTimeLine = 240,
    [pbr::OriginalName("EntityEventType_EntityEventTypeTimeLineShowText")] EntityEventTypeTimeLineShowText = 241,
    [pbr::OriginalName("EntityEventType_EntityEventTypeTimeLineMoveToPos")] EntityEventTypeTimeLineMoveToPos = 242,
    [pbr::OriginalName("EntityEventType_EntityEventTypeTimeLinePlayAudio")] EntityEventTypeTimeLinePlayAudio = 243,
    [pbr::OriginalName("EntityEventType_EntityEventTypeTimeLineShowSubtitle")] EntityEventTypeTimeLineShowSubtitle = 244,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeCGVideoEnd")] EntityEventTypeCodeCgvideoEnd = 245,
    [pbr::OriginalName("EntityEventType_EntityEventTypeQuickCodeRestart")] EntityEventTypeQuickCodeRestart = 246,
    /// <summary>
    /// 隐藏实体
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeHide")] EntityEventTypeHide = 247,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeEventCodeNotification")] EntityEventTypeCodeEventCodeNotification = 355,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeSetProfile")] EntityEventTypeCodeSetProfile = 357,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeSettingPanel")] EntityEventTypeCodeSettingPanel = 358,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeMissionEnd")] EntityEventTypeCodeMissionEnd = 359,
    [pbr::OriginalName("EntityEventType_EntityEventTypeClickOperateBubble")] EntityEventTypeClickOperateBubble = 360,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeCameraAction")] EntityEventTypeCodeCameraAction = 361,
    [pbr::OriginalName("EntityEventType_EntityEventTypePopComplexDiglog")] EntityEventTypePopComplexDiglog = 362,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeSetCarryClass")] EntityEventTypeCodeSetCarryClass = 363,
    /// <summary>
    /// --------------- 机器人 400-409 ----------------------------
    ///通知机器人开始共享机器人视野
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeBotShareViewStart")] EntityEventTypeBotShareViewStart = 400,
    /// <summary>
    ///通知机器人停止共享机器人视野
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeBotShareViewStop")] EntityEventTypeBotShareViewStop = 401,
    [pbr::OriginalName("EntityEventType_EntityEventTypeAddFuel")] EntityEventTypeAddFuel = 403,
    [pbr::OriginalName("EntityEventType_EntityEventTypeBotChangeSkin")] EntityEventTypeBotChangeSkin = 404,
    [pbr::OriginalName("EntityEventType_EntityEventTypeBotRename")] EntityEventTypeBotRename = 405,
    /// <summary>
    /// --------------- 建造 450-459 ------------------------------
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeBuildingSwitch")] EntityEventTypeBuildingSwitch = 450,
    [pbr::OriginalName("EntityEventType_EntityEventTypeBuildingModePosUpdate")] EntityEventTypeBuildingModePosUpdate = 451,
    [pbr::OriginalName("EntityEventType_EntityEventTypeQuitBuildingStatus")] EntityEventTypeQuitBuildingStatus = 452,
    /// <summary>
    /// --------------- 建筑物和工作台 500~549 --------------------
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeWorkbenchObjectUpdate")] EntityEventTypeWorkbenchObjectUpdate = 501,
    [pbr::OriginalName("EntityEventType_EntityEventTypeBuildingWidgetUpdate")] EntityEventTypeBuildingWidgetUpdate = 502,
    [pbr::OriginalName("EntityEventType_EntityEventTypeWorkbenchAddFuel")] EntityEventTypeWorkbenchAddFuel = 512,
    [pbr::OriginalName("EntityEventType_EntityEventTypeWorkbenchComponent")] EntityEventTypeWorkbenchComponent = 513,
    [pbr::OriginalName("EntityEventType_EntityEventTypeWorkbenchResetComponent")] EntityEventTypeWorkbenchResetComponent = 514,
    [pbr::OriginalName("EntityEventType_EntityEventTypeWorkbenchSetPrompt")] EntityEventTypeWorkbenchSetPrompt = 515,
    [pbr::OriginalName("EntityEventType_EntityEventTypeWorkbenchUpdateSub")] EntityEventTypeWorkbenchUpdateSub = 516,
    [pbr::OriginalName("EntityEventType_EntityEventTypeWorkbenchUpdateFather")] EntityEventTypeWorkbenchUpdateFather = 517,
    /// <summary>
    /// --------------- entity场景事件 600 ~ 699 -----------------
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeEntityLock")] EntityEventTypeEntityLock = 600,
    [pbr::OriginalName("EntityEventType_EntityEventTypeEntityUnLock")] EntityEventTypeEntityUnLock = 601,
    [pbr::OriginalName("EntityEventType_EntityEventTypeRegisterEntityCodeEvent")] EntityEventTypeRegisterEntityCodeEvent = 602,
    [pbr::OriginalName("EntityEventType_EntityEventTypeDestroyEntityCodeEvent")] EntityEventTypeDestroyEntityCodeEvent = 603,
    [pbr::OriginalName("EntityEventType_EntityEventTypeBeClick")] EntityEventTypeBeClick = 604,
    [pbr::OriginalName("EntityEventType_EntityEventTypeUpdateAnimation")] EntityEventTypeUpdateAnimation = 605,
    [pbr::OriginalName("EntityEventType_EntityEventTypeBeOperated")] EntityEventTypeBeOperated = 606,
    [pbr::OriginalName("EntityEventType_EntityEventTypeEntityLockUpdate")] EntityEventTypeEntityLockUpdate = 607,
    [pbr::OriginalName("EntityEventType_EntityEventTypeUpdateAudio")] EntityEventTypeUpdateAudio = 608,
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerAddDiyAudio")] EntityEventTypePlayerAddDiyAudio = 609,
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerGetDiyAudio")] EntityEventTypePlayerGetDiyAudio = 610,
    [pbr::OriginalName("EntityEventType_EntityEventTypeUpdateUseEmoji")] EntityEventTypeUpdateUseEmoji = 611,
    [pbr::OriginalName("EntityEventType_EntityEventTypeApplyEntityTemplate")] EntityEventTypeApplyEntityTemplate = 612,
    [pbr::OriginalName("EntityEventType_EntityEventTypeUpdateMapTemplate")] EntityEventTypeUpdateMapTemplate = 613,
    [pbr::OriginalName("EntityEventType_EntityEventTypeMonsterLockPlayer")] EntityEventTypeMonsterLockPlayer = 614,
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerForceExitFight")] EntityEventTypePlayerForceExitFight = 615,
    /// <summary>
    /// --------------- 聊天 1000~1050 ---------------------------
    /// 附近chat 信息
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeSendNearbyChat")] EntityEventTypeSendNearbyChat = 1000,
    [pbr::OriginalName("EntityEventType_EntityEventTypeSendNearToCodeEntitybyChat")] EntityEventTypeSendNearToCodeEntitybyChat = 1001,
    /// <summary>
    /// --------------- 事件号最大值 ---------------
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeNumMax")] EntityEventTypeNumMax = 65535,
  }

  public enum EventCodeType {
    /// <summary>
    /// 指定实体的代码块事件
    /// </summary>
    [pbr::OriginalName("EventCodeType_EventCodeTypeUnknown")] EventCodeTypeUnknown = 0,
    /// <summary>
    /// 指定实体的代码块事件
    /// </summary>
    [pbr::OriginalName("EventCodeType_EventCodeTypeServer")] EventCodeTypeServer = 1,
    /// <summary>
    /// 不指定某个实体的代码块事件
    /// </summary>
    [pbr::OriginalName("EventCodeType_EventCodeTypeEntityEvent")] EventCodeTypeEntityEvent = 2,
    /// <summary>
    /// 接收实体发送的广播呼叫
    /// </summary>
    [pbr::OriginalName("EventCodeType_EventCodeTypeReceiveEventCall")] EventCodeTypeReceiveEventCall = 3,
    /// <summary>
    /// 某类型的实体的事件
    /// </summary>
    [pbr::OriginalName("EventCodeType_EventCodeTypeEntityType")] EventCodeTypeEntityType = 4,
  }

  public enum EntityCodeEventType {
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeUnknown")] EntityCodeEventTypeUnknown = 0,
    /// <summary>
    /// 实体点击事件
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeBeClicked")] EntityCodeEventTypeBeClicked = 101,
    /// <summary>
    /// 实体坐标变更
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypePosUpdate")] EntityCodeEventTypePosUpdate = 102,
    /// <summary>
    /// 实体被攻击
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeBeAttack")] EntityCodeEventTypeBeAttack = 103,
    /// <summary>
    /// 实体攻击
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeAttack")] EntityCodeEventTypeAttack = 104,
    /// <summary>
    /// 实体死亡
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeDead")] EntityCodeEventTypeDead = 105,
    /// <summary>
    /// 实体被操作
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeOnTouch")] EntityCodeEventTypeOnTouch = 106,
    /// <summary>
    /// 实体当前帧更新
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeFrameUpdate")] EntityCodeEventTypeFrameUpdate = 107,
    /// <summary>
    /// 实体能源变更
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeFuelUpdate")] EntityCodeEventTypeFuelUpdate = 108,
    /// <summary>
    /// 实体使用技能
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeUseSkill")] EntityCodeEventTypeUseSkill = 109,
    /// <summary>
    /// 操作失效/生效
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeCanOperate")] EntityCodeEventTypeCanOperate = 110,
    /// <summary>
    /// 镜像
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeMirror")] EntityCodeEventTypeMirror = 112,
    /// <summary>
    /// 合成物品
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeComponent")] EntityCodeEventTypeComponent = 113,
    /// <summary>
    /// 接收广播
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeReceiveEventCall")] EntityCodeEventTypeReceiveEventCall = 114,
    /// <summary>
    /// 变量改变
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeVarChange")] EntityCodeEventTypeVarChange = 115,
    /// <summary>
    /// 实体被实体踩踏
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeEntityBeStampede")] EntityCodeEventTypeEntityBeStampede = 116,
    /// <summary>
    /// 实体被实体踩踏结束
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeEntityOverBeStampede")] EntityCodeEventTypeEntityOverBeStampede = 117,
    /// <summary>
    /// 实体被建造 || 任意实体被建造
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeOnBuild")] EntityCodeEventTypeOnBuild = 118,
    /// <summary>
    /// 实体进入房间
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeEnterRoom")] EntityCodeEventTypeEnterRoom = 119,
    /// <summary>
    /// 输入事件
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeInputKeyAction")] EntityCodeEventTypeInputKeyAction = 121,
    /// <summary>
    /// 按键事件
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeKeypress")] EntityCodeEventTypeKeypress = 122,
    /// <summary>
    /// 实体使用物件
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeUseItem")] EntityCodeEventTypeUseItem = 124,
    /// <summary>
    /// 实体丢弃物件
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeDropItem")] EntityCodeEventTypeDropItem = 125,
    /// <summary>
    /// 实体拾取物件
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypePickupItem")] EntityCodeEventTypePickupItem = 126,
    /// <summary>
    /// 实体碰撞
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeOnCrash")] EntityCodeEventTypeOnCrash = 129,
    /// <summary>
    /// 实体丢弃物件返回物品id
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeDropItemWithId")] EntityCodeEventTypeDropItemWithId = 130,
    /// <summary>
    /// xx克隆体被删除
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeOnCloneDel")] EntityCodeEventTypeOnCloneDel = 131,
    /// <summary>
    /// 实体被拿起
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityEventTypeCodeOnBePickUp")] EntityEventTypeCodeOnBePickUp = 135,
    /// <summary>
    /// 实体被放下
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityEventTypeCodeOnBePutDown")] EntityEventTypeCodeOnBePutDown = 136,
    /// <summary>
    /// 实体被销毁
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityEventTypeCodeOnBeDestroy")] EntityEventTypeCodeOnBeDestroy = 137,
    /// <summary>
    /// 玩家完成答题
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityEventTypeCodePlayerIssueSettle")] EntityEventTypeCodePlayerIssueSettle = 138,
    /// <summary>
    /// 当实体快速编码运行/停止时触发（需打开可编码属性生效）
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityEventTypeEntitiesQuickCodeRunOrStop")] EntityEventTypeEntitiesQuickCodeRunOrStop = 139,
  }

  /// <summary>
  /// 数据保存事件TYPE
  /// </summary>
  public enum DataSaveType {
    [pbr::OriginalName("DataSaveType_DataSaveTypeUnknown")] DataSaveTypeUnknown = 0,
    [pbr::OriginalName("DataSaveType_DataSaveTypeMapGob")] DataSaveTypeMapGob = 1001,
  }

  /// <summary>
  /// 场景作用力消失时机
  /// </summary>
  public enum SceneForceRemoveTime {
    [pbr::OriginalName("SceneForceRemoveTime_SceneForceRemoveTimeUnknown")] SceneForceRemoveTimeUnknown = 0,
    /// <summary>
    /// 离开指定区域
    /// </summary>
    [pbr::OriginalName("SceneForceRemoveTime_SceneForceRemoveTimeLeave")] SceneForceRemoveTimeLeave = 2001,
    /// <summary>
    /// 到达指定目标点
    /// </summary>
    [pbr::OriginalName("SceneForceRemoveTime_SceneForceRemoveTimeTargetRC")] SceneForceRemoveTimeTargetRc = 2002,
    /// <summary>
    /// 持续多少时间
    /// </summary>
    [pbr::OriginalName("SceneForceRemoveTime_SceneForceRemoveTimeRunTime")] SceneForceRemoveTimeRunTime = 2003,
    /// <summary>
    /// 移动多少距离
    /// </summary>
    [pbr::OriginalName("SceneForceRemoveTime_SceneForceRemoveTimeDist")] SceneForceRemoveTimeDist = 2004,
  }

  #endregion

}

#endregion Designer generated code
