// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: server_message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Bian {

  /// <summary>Holder for reflection information generated from server_message.proto</summary>
  public static partial class ServerMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for server_message.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServerMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRzZXJ2ZXJfbWVzc2FnZS5wcm90bxIEQmlhbiLTBAoRU2VydmVyTXNnRW52",
            "ZWxvcGUSEwoLZnJvbV9zZXJ2ZXIYASABKAkSKQoEdHlwZRgCIAEoDjIbLkJp",
            "YW4uU2VydmVyTXNnRW52ZWxvcGVUeXBlEg4KBnNlcV9pZBgDIAEoBRISCgpl",
            "cnJvcl9jb2RlGAQgASgFEhUKDWVycm9yX21lc3NhZ2UYBSABKAkSPQoXc2Vy",
            "dmVyX21zZ19waW5nX3JlcXVlc3QYZCABKAsyGi5CaWFuLlNlcnZlck1zZ1Bp",
            "bmdSZXF1ZXN0SAASPwoYc2VydmVyX21zZ19waW5nX3Jlc3BvbnNlGGUgASgL",
            "MhsuQmlhbi5TZXJ2ZXJNc2dQaW5nUmVzcG9uc2VIABI+Chh0X3NlcnZlcl9t",
            "c2dfc2VydmVyX3N0b3AYZiABKAsyGi5CaWFuLlRTZXJ2ZXJNc2dTZXJ2ZXJT",
            "dG9wSAASOAoVdF9zZXJ2ZXJfbXNnX2tpY2tfb3V0GGcgASgLMhcuQmlhbi5U",
            "U2VydmVyTXNnS2lja091dEgAEl0KKHNlcnZlcl9tc2dfY29tcGxldGVfbWFw",
            "X3RlbXBsYXRlX3JlcXVlc3QYaCABKAsyKS5CaWFuLlNlcnZlck1zZ0NvbXBs",
            "ZXRlTWFwVGVtcGxhdGVSZXF1ZXN0SAASXwopc2VydmVyX21zZ19jb21wbGV0",
            "ZV9tYXBfdGVtcGxhdGVfcmVzcG9uc2UYaSABKAsyKi5CaWFuLlNlcnZlck1z",
            "Z0NvbXBsZXRlTWFwVGVtcGxhdGVSZXNwb25zZUgAQgkKB3BheWxvYWQiFgoU",
            "U2VydmVyTXNnUGluZ1JlcXVlc3QiFwoVU2VydmVyTXNnUGluZ1Jlc3BvbnNl",
            "IikKFFRTZXJ2ZXJNc2dTZXJ2ZXJTdG9wEhEKCXNlcnZlcl9pZBgBIAEoCSIT",
            "ChFUU2VydmVyTXNnS2lja091dCJRCiNTZXJ2ZXJNc2dDb21wbGV0ZU1hcFRl",
            "bXBsYXRlUmVxdWVzdBIRCglwbGF5ZXJfaWQYASABKAkSFwoPbWFwX3RlbXBs",
            "YXRlX2lkGAIgASgJIiYKJFNlcnZlck1zZ0NvbXBsZXRlTWFwVGVtcGxhdGVS",
            "ZXNwb25zZSq9AgoVU2VydmVyTXNnRW52ZWxvcGVUeXBlEjYKMlNlcnZlck1z",
            "Z0VudmVsb3BlVHlwZV9TZXJ2ZXJNc2dFbnZlbG9wZVR5cGVVbmtub3duEAAS",
            "MwovU2VydmVyTXNnRW52ZWxvcGVUeXBlX1NlcnZlck1zZ0VudmVsb3BlVHlw",
            "ZVBpbmcQZBI6CjZTZXJ2ZXJNc2dFbnZlbG9wZVR5cGVfVFNlcnZlck1zZ0Vu",
            "dmVsb3BlVHlwZVNlcnZlclN0b3AQZRI3CjNTZXJ2ZXJNc2dFbnZlbG9wZVR5",
            "cGVfVFNlcnZlck1zZ0VudmVsb3BlVHlwZUtpY2tPdXQQZhJCCj5TZXJ2ZXJN",
            "c2dFbnZlbG9wZVR5cGVfU2VydmVyTXNnRW52ZWxvcGVUeXBlQ29tcGxldGVN",
            "YXBUZW1wbGF0ZRBoYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Bian.ServerMsgEnvelopeType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Bian.ServerMsgEnvelope), global::Bian.ServerMsgEnvelope.Parser, new[]{ "FromServer", "Type", "SeqId", "ErrorCode", "ErrorMessage", "ServerMsgPingRequest", "ServerMsgPingResponse", "TServerMsgServerStop", "TServerMsgKickOut", "ServerMsgCompleteMapTemplateRequest", "ServerMsgCompleteMapTemplateResponse" }, new[]{ "Payload" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bian.ServerMsgPingRequest), global::Bian.ServerMsgPingRequest.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bian.ServerMsgPingResponse), global::Bian.ServerMsgPingResponse.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bian.TServerMsgServerStop), global::Bian.TServerMsgServerStop.Parser, new[]{ "ServerId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bian.TServerMsgKickOut), global::Bian.TServerMsgKickOut.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bian.ServerMsgCompleteMapTemplateRequest), global::Bian.ServerMsgCompleteMapTemplateRequest.Parser, new[]{ "PlayerId", "MapTemplateId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bian.ServerMsgCompleteMapTemplateResponse), global::Bian.ServerMsgCompleteMapTemplateResponse.Parser, null, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ServerMsgEnvelopeType {
    [pbr::OriginalName("ServerMsgEnvelopeType_ServerMsgEnvelopeTypeUnknown")] ServerMsgEnvelopeTypeUnknown = 0,
    /// <summary>
    ///消息号从100开头
    /// </summary>
    [pbr::OriginalName("ServerMsgEnvelopeType_ServerMsgEnvelopeTypePing")] ServerMsgEnvelopeTypePing = 100,
    [pbr::OriginalName("ServerMsgEnvelopeType_TServerMsgEnvelopeTypeServerStop")] TserverMsgEnvelopeTypeServerStop = 101,
    [pbr::OriginalName("ServerMsgEnvelopeType_TServerMsgEnvelopeTypeKickOut")] TserverMsgEnvelopeTypeKickOut = 102,
    [pbr::OriginalName("ServerMsgEnvelopeType_ServerMsgEnvelopeTypeCompleteMapTemplate")] ServerMsgEnvelopeTypeCompleteMapTemplate = 104,
  }

  #endregion

  #region Messages
  /// <summary>
  /// 消息交互体.
  /// </summary>
  public sealed partial class ServerMsgEnvelope : pb::IMessage<ServerMsgEnvelope>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ServerMsgEnvelope> _parser = new pb::MessageParser<ServerMsgEnvelope>(() => new ServerMsgEnvelope());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ServerMsgEnvelope> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bian.ServerMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerMsgEnvelope() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerMsgEnvelope(ServerMsgEnvelope other) : this() {
      fromServer_ = other.fromServer_;
      type_ = other.type_;
      seqId_ = other.seqId_;
      errorCode_ = other.errorCode_;
      errorMessage_ = other.errorMessage_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.ServerMsgPingRequest:
          ServerMsgPingRequest = other.ServerMsgPingRequest.Clone();
          break;
        case PayloadOneofCase.ServerMsgPingResponse:
          ServerMsgPingResponse = other.ServerMsgPingResponse.Clone();
          break;
        case PayloadOneofCase.TServerMsgServerStop:
          TServerMsgServerStop = other.TServerMsgServerStop.Clone();
          break;
        case PayloadOneofCase.TServerMsgKickOut:
          TServerMsgKickOut = other.TServerMsgKickOut.Clone();
          break;
        case PayloadOneofCase.ServerMsgCompleteMapTemplateRequest:
          ServerMsgCompleteMapTemplateRequest = other.ServerMsgCompleteMapTemplateRequest.Clone();
          break;
        case PayloadOneofCase.ServerMsgCompleteMapTemplateResponse:
          ServerMsgCompleteMapTemplateResponse = other.ServerMsgCompleteMapTemplateResponse.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerMsgEnvelope Clone() {
      return new ServerMsgEnvelope(this);
    }

    /// <summary>Field number for the "from_server" field.</summary>
    public const int FromServerFieldNumber = 1;
    private string fromServer_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FromServer {
      get { return fromServer_; }
      set {
        fromServer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::Bian.ServerMsgEnvelopeType type_ = global::Bian.ServerMsgEnvelopeType.ServerMsgEnvelopeTypeUnknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bian.ServerMsgEnvelopeType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "seq_id" field.</summary>
    public const int SeqIdFieldNumber = 3;
    private int seqId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SeqId {
      get { return seqId_; }
      set {
        seqId_ = value;
      }
    }

    /// <summary>Field number for the "error_code" field.</summary>
    public const int ErrorCodeFieldNumber = 4;
    private int errorCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ErrorCode {
      get { return errorCode_; }
      set {
        errorCode_ = value;
      }
    }

    /// <summary>Field number for the "error_message" field.</summary>
    public const int ErrorMessageFieldNumber = 5;
    private string errorMessage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ErrorMessage {
      get { return errorMessage_; }
      set {
        errorMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "server_msg_ping_request" field.</summary>
    public const int ServerMsgPingRequestFieldNumber = 100;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bian.ServerMsgPingRequest ServerMsgPingRequest {
      get { return payloadCase_ == PayloadOneofCase.ServerMsgPingRequest ? (global::Bian.ServerMsgPingRequest) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.ServerMsgPingRequest;
      }
    }

    /// <summary>Field number for the "server_msg_ping_response" field.</summary>
    public const int ServerMsgPingResponseFieldNumber = 101;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bian.ServerMsgPingResponse ServerMsgPingResponse {
      get { return payloadCase_ == PayloadOneofCase.ServerMsgPingResponse ? (global::Bian.ServerMsgPingResponse) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.ServerMsgPingResponse;
      }
    }

    /// <summary>Field number for the "t_server_msg_server_stop" field.</summary>
    public const int TServerMsgServerStopFieldNumber = 102;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bian.TServerMsgServerStop TServerMsgServerStop {
      get { return payloadCase_ == PayloadOneofCase.TServerMsgServerStop ? (global::Bian.TServerMsgServerStop) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.TServerMsgServerStop;
      }
    }

    /// <summary>Field number for the "t_server_msg_kick_out" field.</summary>
    public const int TServerMsgKickOutFieldNumber = 103;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bian.TServerMsgKickOut TServerMsgKickOut {
      get { return payloadCase_ == PayloadOneofCase.TServerMsgKickOut ? (global::Bian.TServerMsgKickOut) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.TServerMsgKickOut;
      }
    }

    /// <summary>Field number for the "server_msg_complete_map_template_request" field.</summary>
    public const int ServerMsgCompleteMapTemplateRequestFieldNumber = 104;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bian.ServerMsgCompleteMapTemplateRequest ServerMsgCompleteMapTemplateRequest {
      get { return payloadCase_ == PayloadOneofCase.ServerMsgCompleteMapTemplateRequest ? (global::Bian.ServerMsgCompleteMapTemplateRequest) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.ServerMsgCompleteMapTemplateRequest;
      }
    }

    /// <summary>Field number for the "server_msg_complete_map_template_response" field.</summary>
    public const int ServerMsgCompleteMapTemplateResponseFieldNumber = 105;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bian.ServerMsgCompleteMapTemplateResponse ServerMsgCompleteMapTemplateResponse {
      get { return payloadCase_ == PayloadOneofCase.ServerMsgCompleteMapTemplateResponse ? (global::Bian.ServerMsgCompleteMapTemplateResponse) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.ServerMsgCompleteMapTemplateResponse;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      ServerMsgPingRequest = 100,
      ServerMsgPingResponse = 101,
      TServerMsgServerStop = 102,
      TServerMsgKickOut = 103,
      ServerMsgCompleteMapTemplateRequest = 104,
      ServerMsgCompleteMapTemplateResponse = 105,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ServerMsgEnvelope);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ServerMsgEnvelope other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FromServer != other.FromServer) return false;
      if (Type != other.Type) return false;
      if (SeqId != other.SeqId) return false;
      if (ErrorCode != other.ErrorCode) return false;
      if (ErrorMessage != other.ErrorMessage) return false;
      if (!object.Equals(ServerMsgPingRequest, other.ServerMsgPingRequest)) return false;
      if (!object.Equals(ServerMsgPingResponse, other.ServerMsgPingResponse)) return false;
      if (!object.Equals(TServerMsgServerStop, other.TServerMsgServerStop)) return false;
      if (!object.Equals(TServerMsgKickOut, other.TServerMsgKickOut)) return false;
      if (!object.Equals(ServerMsgCompleteMapTemplateRequest, other.ServerMsgCompleteMapTemplateRequest)) return false;
      if (!object.Equals(ServerMsgCompleteMapTemplateResponse, other.ServerMsgCompleteMapTemplateResponse)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FromServer.Length != 0) hash ^= FromServer.GetHashCode();
      if (Type != global::Bian.ServerMsgEnvelopeType.ServerMsgEnvelopeTypeUnknown) hash ^= Type.GetHashCode();
      if (SeqId != 0) hash ^= SeqId.GetHashCode();
      if (ErrorCode != 0) hash ^= ErrorCode.GetHashCode();
      if (ErrorMessage.Length != 0) hash ^= ErrorMessage.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.ServerMsgPingRequest) hash ^= ServerMsgPingRequest.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.ServerMsgPingResponse) hash ^= ServerMsgPingResponse.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.TServerMsgServerStop) hash ^= TServerMsgServerStop.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.TServerMsgKickOut) hash ^= TServerMsgKickOut.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.ServerMsgCompleteMapTemplateRequest) hash ^= ServerMsgCompleteMapTemplateRequest.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.ServerMsgCompleteMapTemplateResponse) hash ^= ServerMsgCompleteMapTemplateResponse.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FromServer.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FromServer);
      }
      if (Type != global::Bian.ServerMsgEnvelopeType.ServerMsgEnvelopeTypeUnknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (SeqId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SeqId);
      }
      if (ErrorCode != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ErrorCode);
      }
      if (ErrorMessage.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ErrorMessage);
      }
      if (payloadCase_ == PayloadOneofCase.ServerMsgPingRequest) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(ServerMsgPingRequest);
      }
      if (payloadCase_ == PayloadOneofCase.ServerMsgPingResponse) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(ServerMsgPingResponse);
      }
      if (payloadCase_ == PayloadOneofCase.TServerMsgServerStop) {
        output.WriteRawTag(178, 6);
        output.WriteMessage(TServerMsgServerStop);
      }
      if (payloadCase_ == PayloadOneofCase.TServerMsgKickOut) {
        output.WriteRawTag(186, 6);
        output.WriteMessage(TServerMsgKickOut);
      }
      if (payloadCase_ == PayloadOneofCase.ServerMsgCompleteMapTemplateRequest) {
        output.WriteRawTag(194, 6);
        output.WriteMessage(ServerMsgCompleteMapTemplateRequest);
      }
      if (payloadCase_ == PayloadOneofCase.ServerMsgCompleteMapTemplateResponse) {
        output.WriteRawTag(202, 6);
        output.WriteMessage(ServerMsgCompleteMapTemplateResponse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FromServer.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FromServer);
      }
      if (Type != global::Bian.ServerMsgEnvelopeType.ServerMsgEnvelopeTypeUnknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (SeqId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SeqId);
      }
      if (ErrorCode != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ErrorCode);
      }
      if (ErrorMessage.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ErrorMessage);
      }
      if (payloadCase_ == PayloadOneofCase.ServerMsgPingRequest) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(ServerMsgPingRequest);
      }
      if (payloadCase_ == PayloadOneofCase.ServerMsgPingResponse) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(ServerMsgPingResponse);
      }
      if (payloadCase_ == PayloadOneofCase.TServerMsgServerStop) {
        output.WriteRawTag(178, 6);
        output.WriteMessage(TServerMsgServerStop);
      }
      if (payloadCase_ == PayloadOneofCase.TServerMsgKickOut) {
        output.WriteRawTag(186, 6);
        output.WriteMessage(TServerMsgKickOut);
      }
      if (payloadCase_ == PayloadOneofCase.ServerMsgCompleteMapTemplateRequest) {
        output.WriteRawTag(194, 6);
        output.WriteMessage(ServerMsgCompleteMapTemplateRequest);
      }
      if (payloadCase_ == PayloadOneofCase.ServerMsgCompleteMapTemplateResponse) {
        output.WriteRawTag(202, 6);
        output.WriteMessage(ServerMsgCompleteMapTemplateResponse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FromServer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FromServer);
      }
      if (Type != global::Bian.ServerMsgEnvelopeType.ServerMsgEnvelopeTypeUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (SeqId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SeqId);
      }
      if (ErrorCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ErrorCode);
      }
      if (ErrorMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorMessage);
      }
      if (payloadCase_ == PayloadOneofCase.ServerMsgPingRequest) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ServerMsgPingRequest);
      }
      if (payloadCase_ == PayloadOneofCase.ServerMsgPingResponse) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ServerMsgPingResponse);
      }
      if (payloadCase_ == PayloadOneofCase.TServerMsgServerStop) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(TServerMsgServerStop);
      }
      if (payloadCase_ == PayloadOneofCase.TServerMsgKickOut) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(TServerMsgKickOut);
      }
      if (payloadCase_ == PayloadOneofCase.ServerMsgCompleteMapTemplateRequest) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ServerMsgCompleteMapTemplateRequest);
      }
      if (payloadCase_ == PayloadOneofCase.ServerMsgCompleteMapTemplateResponse) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ServerMsgCompleteMapTemplateResponse);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ServerMsgEnvelope other) {
      if (other == null) {
        return;
      }
      if (other.FromServer.Length != 0) {
        FromServer = other.FromServer;
      }
      if (other.Type != global::Bian.ServerMsgEnvelopeType.ServerMsgEnvelopeTypeUnknown) {
        Type = other.Type;
      }
      if (other.SeqId != 0) {
        SeqId = other.SeqId;
      }
      if (other.ErrorCode != 0) {
        ErrorCode = other.ErrorCode;
      }
      if (other.ErrorMessage.Length != 0) {
        ErrorMessage = other.ErrorMessage;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.ServerMsgPingRequest:
          if (ServerMsgPingRequest == null) {
            ServerMsgPingRequest = new global::Bian.ServerMsgPingRequest();
          }
          ServerMsgPingRequest.MergeFrom(other.ServerMsgPingRequest);
          break;
        case PayloadOneofCase.ServerMsgPingResponse:
          if (ServerMsgPingResponse == null) {
            ServerMsgPingResponse = new global::Bian.ServerMsgPingResponse();
          }
          ServerMsgPingResponse.MergeFrom(other.ServerMsgPingResponse);
          break;
        case PayloadOneofCase.TServerMsgServerStop:
          if (TServerMsgServerStop == null) {
            TServerMsgServerStop = new global::Bian.TServerMsgServerStop();
          }
          TServerMsgServerStop.MergeFrom(other.TServerMsgServerStop);
          break;
        case PayloadOneofCase.TServerMsgKickOut:
          if (TServerMsgKickOut == null) {
            TServerMsgKickOut = new global::Bian.TServerMsgKickOut();
          }
          TServerMsgKickOut.MergeFrom(other.TServerMsgKickOut);
          break;
        case PayloadOneofCase.ServerMsgCompleteMapTemplateRequest:
          if (ServerMsgCompleteMapTemplateRequest == null) {
            ServerMsgCompleteMapTemplateRequest = new global::Bian.ServerMsgCompleteMapTemplateRequest();
          }
          ServerMsgCompleteMapTemplateRequest.MergeFrom(other.ServerMsgCompleteMapTemplateRequest);
          break;
        case PayloadOneofCase.ServerMsgCompleteMapTemplateResponse:
          if (ServerMsgCompleteMapTemplateResponse == null) {
            ServerMsgCompleteMapTemplateResponse = new global::Bian.ServerMsgCompleteMapTemplateResponse();
          }
          ServerMsgCompleteMapTemplateResponse.MergeFrom(other.ServerMsgCompleteMapTemplateResponse);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FromServer = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::Bian.ServerMsgEnvelopeType) input.ReadEnum();
            break;
          }
          case 24: {
            SeqId = input.ReadInt32();
            break;
          }
          case 32: {
            ErrorCode = input.ReadInt32();
            break;
          }
          case 42: {
            ErrorMessage = input.ReadString();
            break;
          }
          case 802: {
            global::Bian.ServerMsgPingRequest subBuilder = new global::Bian.ServerMsgPingRequest();
            if (payloadCase_ == PayloadOneofCase.ServerMsgPingRequest) {
              subBuilder.MergeFrom(ServerMsgPingRequest);
            }
            input.ReadMessage(subBuilder);
            ServerMsgPingRequest = subBuilder;
            break;
          }
          case 810: {
            global::Bian.ServerMsgPingResponse subBuilder = new global::Bian.ServerMsgPingResponse();
            if (payloadCase_ == PayloadOneofCase.ServerMsgPingResponse) {
              subBuilder.MergeFrom(ServerMsgPingResponse);
            }
            input.ReadMessage(subBuilder);
            ServerMsgPingResponse = subBuilder;
            break;
          }
          case 818: {
            global::Bian.TServerMsgServerStop subBuilder = new global::Bian.TServerMsgServerStop();
            if (payloadCase_ == PayloadOneofCase.TServerMsgServerStop) {
              subBuilder.MergeFrom(TServerMsgServerStop);
            }
            input.ReadMessage(subBuilder);
            TServerMsgServerStop = subBuilder;
            break;
          }
          case 826: {
            global::Bian.TServerMsgKickOut subBuilder = new global::Bian.TServerMsgKickOut();
            if (payloadCase_ == PayloadOneofCase.TServerMsgKickOut) {
              subBuilder.MergeFrom(TServerMsgKickOut);
            }
            input.ReadMessage(subBuilder);
            TServerMsgKickOut = subBuilder;
            break;
          }
          case 834: {
            global::Bian.ServerMsgCompleteMapTemplateRequest subBuilder = new global::Bian.ServerMsgCompleteMapTemplateRequest();
            if (payloadCase_ == PayloadOneofCase.ServerMsgCompleteMapTemplateRequest) {
              subBuilder.MergeFrom(ServerMsgCompleteMapTemplateRequest);
            }
            input.ReadMessage(subBuilder);
            ServerMsgCompleteMapTemplateRequest = subBuilder;
            break;
          }
          case 842: {
            global::Bian.ServerMsgCompleteMapTemplateResponse subBuilder = new global::Bian.ServerMsgCompleteMapTemplateResponse();
            if (payloadCase_ == PayloadOneofCase.ServerMsgCompleteMapTemplateResponse) {
              subBuilder.MergeFrom(ServerMsgCompleteMapTemplateResponse);
            }
            input.ReadMessage(subBuilder);
            ServerMsgCompleteMapTemplateResponse = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            FromServer = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::Bian.ServerMsgEnvelopeType) input.ReadEnum();
            break;
          }
          case 24: {
            SeqId = input.ReadInt32();
            break;
          }
          case 32: {
            ErrorCode = input.ReadInt32();
            break;
          }
          case 42: {
            ErrorMessage = input.ReadString();
            break;
          }
          case 802: {
            global::Bian.ServerMsgPingRequest subBuilder = new global::Bian.ServerMsgPingRequest();
            if (payloadCase_ == PayloadOneofCase.ServerMsgPingRequest) {
              subBuilder.MergeFrom(ServerMsgPingRequest);
            }
            input.ReadMessage(subBuilder);
            ServerMsgPingRequest = subBuilder;
            break;
          }
          case 810: {
            global::Bian.ServerMsgPingResponse subBuilder = new global::Bian.ServerMsgPingResponse();
            if (payloadCase_ == PayloadOneofCase.ServerMsgPingResponse) {
              subBuilder.MergeFrom(ServerMsgPingResponse);
            }
            input.ReadMessage(subBuilder);
            ServerMsgPingResponse = subBuilder;
            break;
          }
          case 818: {
            global::Bian.TServerMsgServerStop subBuilder = new global::Bian.TServerMsgServerStop();
            if (payloadCase_ == PayloadOneofCase.TServerMsgServerStop) {
              subBuilder.MergeFrom(TServerMsgServerStop);
            }
            input.ReadMessage(subBuilder);
            TServerMsgServerStop = subBuilder;
            break;
          }
          case 826: {
            global::Bian.TServerMsgKickOut subBuilder = new global::Bian.TServerMsgKickOut();
            if (payloadCase_ == PayloadOneofCase.TServerMsgKickOut) {
              subBuilder.MergeFrom(TServerMsgKickOut);
            }
            input.ReadMessage(subBuilder);
            TServerMsgKickOut = subBuilder;
            break;
          }
          case 834: {
            global::Bian.ServerMsgCompleteMapTemplateRequest subBuilder = new global::Bian.ServerMsgCompleteMapTemplateRequest();
            if (payloadCase_ == PayloadOneofCase.ServerMsgCompleteMapTemplateRequest) {
              subBuilder.MergeFrom(ServerMsgCompleteMapTemplateRequest);
            }
            input.ReadMessage(subBuilder);
            ServerMsgCompleteMapTemplateRequest = subBuilder;
            break;
          }
          case 842: {
            global::Bian.ServerMsgCompleteMapTemplateResponse subBuilder = new global::Bian.ServerMsgCompleteMapTemplateResponse();
            if (payloadCase_ == PayloadOneofCase.ServerMsgCompleteMapTemplateResponse) {
              subBuilder.MergeFrom(ServerMsgCompleteMapTemplateResponse);
            }
            input.ReadMessage(subBuilder);
            ServerMsgCompleteMapTemplateResponse = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ServerMsgPingRequest : pb::IMessage<ServerMsgPingRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ServerMsgPingRequest> _parser = new pb::MessageParser<ServerMsgPingRequest>(() => new ServerMsgPingRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ServerMsgPingRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bian.ServerMessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerMsgPingRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerMsgPingRequest(ServerMsgPingRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerMsgPingRequest Clone() {
      return new ServerMsgPingRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ServerMsgPingRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ServerMsgPingRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ServerMsgPingRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class ServerMsgPingResponse : pb::IMessage<ServerMsgPingResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ServerMsgPingResponse> _parser = new pb::MessageParser<ServerMsgPingResponse>(() => new ServerMsgPingResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ServerMsgPingResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bian.ServerMessageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerMsgPingResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerMsgPingResponse(ServerMsgPingResponse other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerMsgPingResponse Clone() {
      return new ServerMsgPingResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ServerMsgPingResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ServerMsgPingResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ServerMsgPingResponse other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class TServerMsgServerStop : pb::IMessage<TServerMsgServerStop>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TServerMsgServerStop> _parser = new pb::MessageParser<TServerMsgServerStop>(() => new TServerMsgServerStop());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TServerMsgServerStop> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bian.ServerMessageReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TServerMsgServerStop() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TServerMsgServerStop(TServerMsgServerStop other) : this() {
      serverId_ = other.serverId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TServerMsgServerStop Clone() {
      return new TServerMsgServerStop(this);
    }

    /// <summary>Field number for the "server_id" field.</summary>
    public const int ServerIdFieldNumber = 1;
    private string serverId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ServerId {
      get { return serverId_; }
      set {
        serverId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TServerMsgServerStop);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TServerMsgServerStop other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ServerId != other.ServerId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ServerId.Length != 0) hash ^= ServerId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ServerId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ServerId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ServerId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ServerId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ServerId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ServerId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TServerMsgServerStop other) {
      if (other == null) {
        return;
      }
      if (other.ServerId.Length != 0) {
        ServerId = other.ServerId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ServerId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ServerId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TServerMsgKickOut : pb::IMessage<TServerMsgKickOut>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TServerMsgKickOut> _parser = new pb::MessageParser<TServerMsgKickOut>(() => new TServerMsgKickOut());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TServerMsgKickOut> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bian.ServerMessageReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TServerMsgKickOut() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TServerMsgKickOut(TServerMsgKickOut other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TServerMsgKickOut Clone() {
      return new TServerMsgKickOut(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TServerMsgKickOut);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TServerMsgKickOut other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TServerMsgKickOut other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class ServerMsgCompleteMapTemplateRequest : pb::IMessage<ServerMsgCompleteMapTemplateRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ServerMsgCompleteMapTemplateRequest> _parser = new pb::MessageParser<ServerMsgCompleteMapTemplateRequest>(() => new ServerMsgCompleteMapTemplateRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ServerMsgCompleteMapTemplateRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bian.ServerMessageReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerMsgCompleteMapTemplateRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerMsgCompleteMapTemplateRequest(ServerMsgCompleteMapTemplateRequest other) : this() {
      playerId_ = other.playerId_;
      mapTemplateId_ = other.mapTemplateId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerMsgCompleteMapTemplateRequest Clone() {
      return new ServerMsgCompleteMapTemplateRequest(this);
    }

    /// <summary>Field number for the "player_id" field.</summary>
    public const int PlayerIdFieldNumber = 1;
    private string playerId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PlayerId {
      get { return playerId_; }
      set {
        playerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "map_template_id" field.</summary>
    public const int MapTemplateIdFieldNumber = 2;
    private string mapTemplateId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MapTemplateId {
      get { return mapTemplateId_; }
      set {
        mapTemplateId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ServerMsgCompleteMapTemplateRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ServerMsgCompleteMapTemplateRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerId != other.PlayerId) return false;
      if (MapTemplateId != other.MapTemplateId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerId.Length != 0) hash ^= PlayerId.GetHashCode();
      if (MapTemplateId.Length != 0) hash ^= MapTemplateId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PlayerId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PlayerId);
      }
      if (MapTemplateId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MapTemplateId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PlayerId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PlayerId);
      }
      if (MapTemplateId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MapTemplateId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PlayerId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PlayerId);
      }
      if (MapTemplateId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MapTemplateId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ServerMsgCompleteMapTemplateRequest other) {
      if (other == null) {
        return;
      }
      if (other.PlayerId.Length != 0) {
        PlayerId = other.PlayerId;
      }
      if (other.MapTemplateId.Length != 0) {
        MapTemplateId = other.MapTemplateId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PlayerId = input.ReadString();
            break;
          }
          case 18: {
            MapTemplateId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            PlayerId = input.ReadString();
            break;
          }
          case 18: {
            MapTemplateId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ServerMsgCompleteMapTemplateResponse : pb::IMessage<ServerMsgCompleteMapTemplateResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ServerMsgCompleteMapTemplateResponse> _parser = new pb::MessageParser<ServerMsgCompleteMapTemplateResponse>(() => new ServerMsgCompleteMapTemplateResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ServerMsgCompleteMapTemplateResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bian.ServerMessageReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerMsgCompleteMapTemplateResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerMsgCompleteMapTemplateResponse(ServerMsgCompleteMapTemplateResponse other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerMsgCompleteMapTemplateResponse Clone() {
      return new ServerMsgCompleteMapTemplateResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ServerMsgCompleteMapTemplateResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ServerMsgCompleteMapTemplateResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ServerMsgCompleteMapTemplateResponse other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
