// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: task.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Bian {

  /// <summary>Holder for reflection information generated from task.proto</summary>
  public static partial class TaskReflection {

    #region Descriptor
    /// <summary>File descriptor for task.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TaskReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgp0YXNrLnByb3RvEgRCaWFuIkIKEVRhc2tPYmplY3RpdmVJdGVtEhAKCGl0",
            "ZW1fY2lkGAEgASgFEgsKA251bRgCIAEoBRIOCgZuZnRfaWQYAyABKAkiNAoU",
            "VGFza09iamVjdGl2ZU1vbnN0ZXISDwoHbW9uX2NpZBgBIAEoBRILCgNudW0Y",
            "AiABKAUiKwoTVGFza09iamVjdGl2ZU1vdmVUbxIJCgFyGAEgASgFEgkKAWMY",
            "AiABKAUiOAoRVGFza09iamVjdGl2ZVF1aXoSEQoJcXVpel90eXBlGAEgASgF",
            "EhAKCHF1aXpfbnVtGAIgASgFIvcBCgtUYXNrU2V0dGluZxIcCgRraW5kGAEg",
            "ASgOMg4uQmlhbi5UYXNrVHlwZRINCgNudW0YCyABKAVIABInCgRpdGVtGAwg",
            "ASgLMhcuQmlhbi5UYXNrT2JqZWN0aXZlSXRlbUgAEi4KCG1vbl9pbmZvGA0g",
            "ASgLMhouQmlhbi5UYXNrT2JqZWN0aXZlTW9uc3RlckgAEiwKB3Rhcl9wb3MY",
            "DiABKAsyGS5CaWFuLlRhc2tPYmplY3RpdmVNb3ZlVG9IABIsCglxdWl6X2lu",
            "Zm8YDyABKAsyFy5CaWFuLlRhc2tPYmplY3RpdmVRdWl6SABCBgoEZGF0YSJi",
            "CgRUYXNrEgoKAmlkGAEgASgFEhwKBGtpbmQYAiABKA4yDi5CaWFuLlRhc2tU",
            "eXBlEiIKB3NldHRpbmcYAyABKAsyES5CaWFuLlRhc2tTZXR0aW5nEgwKBHJh",
            "dGUYBCABKAUifAoIVGFza0xpc3QSCgoCaWQYASABKAUSIAoEa2luZBgCIAEo",
            "DjISLkJpYW4uVGFza0xpc3RUeXBlEgwKBHJhdGUYAyABKAUSHAoIY3VyX3Rh",
            "c2sYBCABKAsyCi5CaWFuLlRhc2sSFgoOcmVjZWl2ZV9yZXdhcmQYBSABKAUi",
            "MAoKUGxheWVyVGFzaxIiCgp0YXNrX2xpc3RzGAEgAygLMg4uQmlhbi5UYXNr",
            "TGlzdCrhAQoIVGFza1R5cGUSHAoYVGFza1R5cGVfVGFza1R5cGVVbmtub3du",
            "EAASHAoYVGFza1R5cGVfVGFza1R5cGVHZXRJdGVtEAESHAoYVGFza1R5cGVf",
            "VGFza1R5cGVVc2VJdGVtEAISIAocVGFza1R5cGVfVGFza1R5cGVLaWxsTW9u",
            "c3RlchADEhsKF1Rhc2tUeXBlX1Rhc2tUeXBlTW92ZVRvEAQSGQoVVGFza1R5",
            "cGVfVGFza1R5cGVRdWl6EAUSIQodVGFza1R5cGVfVGFza1R5cGVPY2N1cGll",
            "ZExhbmQQBiqjAQoMVGFza0xpc3RUeXBlEiQKIFRhc2tMaXN0VHlwZV9UYXNr",
            "TGlzdFR5cGVVbmtub3duEAASIgoeVGFza0xpc3RUeXBlX1Rhc2tMaXN0VHlw",
            "ZURhaWx5EAESJQohVGFza0xpc3RUeXBlX1Rhc2tMaXN0VHlwZVJld2FyZGVk",
            "EAISIgoeVGFza0xpc3RUeXBlX1Rhc2tMaXN0VHlwZU90aGVyEANiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Bian.TaskType), typeof(global::Bian.TaskListType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Bian.TaskObjectiveItem), global::Bian.TaskObjectiveItem.Parser, new[]{ "ItemCid", "Num", "NftId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bian.TaskObjectiveMonster), global::Bian.TaskObjectiveMonster.Parser, new[]{ "MonCid", "Num" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bian.TaskObjectiveMoveTo), global::Bian.TaskObjectiveMoveTo.Parser, new[]{ "R", "C" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bian.TaskObjectiveQuiz), global::Bian.TaskObjectiveQuiz.Parser, new[]{ "QuizType", "QuizNum" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bian.TaskSetting), global::Bian.TaskSetting.Parser, new[]{ "Kind", "Num", "Item", "MonInfo", "TarPos", "QuizInfo" }, new[]{ "Data" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bian.Task), global::Bian.Task.Parser, new[]{ "Id", "Kind", "Setting", "Rate" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bian.TaskList), global::Bian.TaskList.Parser, new[]{ "Id", "Kind", "Rate", "CurTask", "ReceiveReward" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bian.PlayerTask), global::Bian.PlayerTask.Parser, new[]{ "TaskLists" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum TaskType {
    [pbr::OriginalName("TaskType_TaskTypeUnknown")] TaskTypeUnknown = 0,
    /// <summary>
    /// 寻物任务
    /// </summary>
    [pbr::OriginalName("TaskType_TaskTypeGetItem")] TaskTypeGetItem = 1,
    /// <summary>
    /// 使用道具
    /// </summary>
    [pbr::OriginalName("TaskType_TaskTypeUseItem")] TaskTypeUseItem = 2,
    /// <summary>
    /// 打怪任务
    /// </summary>
    [pbr::OriginalName("TaskType_TaskTypeKillMonster")] TaskTypeKillMonster = 3,
    /// <summary>
    /// 寻路任务
    /// </summary>
    [pbr::OriginalName("TaskType_TaskTypeMoveTo")] TaskTypeMoveTo = 4,
    /// <summary>
    /// Quiz
    /// </summary>
    [pbr::OriginalName("TaskType_TaskTypeQuiz")] TaskTypeQuiz = 5,
    /// <summary>
    /// 攻占地块
    /// </summary>
    [pbr::OriginalName("TaskType_TaskTypeOccupiedLand")] TaskTypeOccupiedLand = 6,
  }

  public enum TaskListType {
    [pbr::OriginalName("TaskListType_TaskListTypeUnknown")] TaskListTypeUnknown = 0,
    /// <summary>
    /// 每日任务
    /// </summary>
    [pbr::OriginalName("TaskListType_TaskListTypeDaily")] TaskListTypeDaily = 1,
    /// <summary>
    /// 悬赏任务
    /// </summary>
    [pbr::OriginalName("TaskListType_TaskListTypeRewarded")] TaskListTypeRewarded = 2,
    /// <summary>
    /// other任务
    /// </summary>
    [pbr::OriginalName("TaskListType_TaskListTypeOther")] TaskListTypeOther = 3,
  }

  #endregion

  #region Messages
  public sealed partial class TaskObjectiveItem : pb::IMessage<TaskObjectiveItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TaskObjectiveItem> _parser = new pb::MessageParser<TaskObjectiveItem>(() => new TaskObjectiveItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TaskObjectiveItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bian.TaskReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskObjectiveItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskObjectiveItem(TaskObjectiveItem other) : this() {
      itemCid_ = other.itemCid_;
      num_ = other.num_;
      nftId_ = other.nftId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskObjectiveItem Clone() {
      return new TaskObjectiveItem(this);
    }

    /// <summary>Field number for the "item_cid" field.</summary>
    public const int ItemCidFieldNumber = 1;
    private int itemCid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ItemCid {
      get { return itemCid_; }
      set {
        itemCid_ = value;
      }
    }

    /// <summary>Field number for the "num" field.</summary>
    public const int NumFieldNumber = 2;
    private int num_;
    /// <summary>
    /// max 10
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Num {
      get { return num_; }
      set {
        num_ = value;
      }
    }

    /// <summary>Field number for the "nft_id" field.</summary>
    public const int NftIdFieldNumber = 3;
    private string nftId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NftId {
      get { return nftId_; }
      set {
        nftId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TaskObjectiveItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TaskObjectiveItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ItemCid != other.ItemCid) return false;
      if (Num != other.Num) return false;
      if (NftId != other.NftId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ItemCid != 0) hash ^= ItemCid.GetHashCode();
      if (Num != 0) hash ^= Num.GetHashCode();
      if (NftId.Length != 0) hash ^= NftId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ItemCid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ItemCid);
      }
      if (Num != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Num);
      }
      if (NftId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NftId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ItemCid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ItemCid);
      }
      if (Num != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Num);
      }
      if (NftId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NftId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ItemCid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemCid);
      }
      if (Num != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Num);
      }
      if (NftId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NftId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TaskObjectiveItem other) {
      if (other == null) {
        return;
      }
      if (other.ItemCid != 0) {
        ItemCid = other.ItemCid;
      }
      if (other.Num != 0) {
        Num = other.Num;
      }
      if (other.NftId.Length != 0) {
        NftId = other.NftId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ItemCid = input.ReadInt32();
            break;
          }
          case 16: {
            Num = input.ReadInt32();
            break;
          }
          case 26: {
            NftId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ItemCid = input.ReadInt32();
            break;
          }
          case 16: {
            Num = input.ReadInt32();
            break;
          }
          case 26: {
            NftId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TaskObjectiveMonster : pb::IMessage<TaskObjectiveMonster>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TaskObjectiveMonster> _parser = new pb::MessageParser<TaskObjectiveMonster>(() => new TaskObjectiveMonster());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TaskObjectiveMonster> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bian.TaskReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskObjectiveMonster() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskObjectiveMonster(TaskObjectiveMonster other) : this() {
      monCid_ = other.monCid_;
      num_ = other.num_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskObjectiveMonster Clone() {
      return new TaskObjectiveMonster(this);
    }

    /// <summary>Field number for the "mon_cid" field.</summary>
    public const int MonCidFieldNumber = 1;
    private int monCid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MonCid {
      get { return monCid_; }
      set {
        monCid_ = value;
      }
    }

    /// <summary>Field number for the "num" field.</summary>
    public const int NumFieldNumber = 2;
    private int num_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Num {
      get { return num_; }
      set {
        num_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TaskObjectiveMonster);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TaskObjectiveMonster other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MonCid != other.MonCid) return false;
      if (Num != other.Num) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MonCid != 0) hash ^= MonCid.GetHashCode();
      if (Num != 0) hash ^= Num.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MonCid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MonCid);
      }
      if (Num != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Num);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MonCid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MonCid);
      }
      if (Num != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Num);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MonCid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MonCid);
      }
      if (Num != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Num);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TaskObjectiveMonster other) {
      if (other == null) {
        return;
      }
      if (other.MonCid != 0) {
        MonCid = other.MonCid;
      }
      if (other.Num != 0) {
        Num = other.Num;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MonCid = input.ReadInt32();
            break;
          }
          case 16: {
            Num = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MonCid = input.ReadInt32();
            break;
          }
          case 16: {
            Num = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TaskObjectiveMoveTo : pb::IMessage<TaskObjectiveMoveTo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TaskObjectiveMoveTo> _parser = new pb::MessageParser<TaskObjectiveMoveTo>(() => new TaskObjectiveMoveTo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TaskObjectiveMoveTo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bian.TaskReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskObjectiveMoveTo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskObjectiveMoveTo(TaskObjectiveMoveTo other) : this() {
      r_ = other.r_;
      c_ = other.c_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskObjectiveMoveTo Clone() {
      return new TaskObjectiveMoveTo(this);
    }

    /// <summary>Field number for the "r" field.</summary>
    public const int RFieldNumber = 1;
    private int r_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int R {
      get { return r_; }
      set {
        r_ = value;
      }
    }

    /// <summary>Field number for the "c" field.</summary>
    public const int CFieldNumber = 2;
    private int c_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int C {
      get { return c_; }
      set {
        c_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TaskObjectiveMoveTo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TaskObjectiveMoveTo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (R != other.R) return false;
      if (C != other.C) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (R != 0) hash ^= R.GetHashCode();
      if (C != 0) hash ^= C.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (R != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(R);
      }
      if (C != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(C);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (R != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(R);
      }
      if (C != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(C);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (R != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(R);
      }
      if (C != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(C);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TaskObjectiveMoveTo other) {
      if (other == null) {
        return;
      }
      if (other.R != 0) {
        R = other.R;
      }
      if (other.C != 0) {
        C = other.C;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            R = input.ReadInt32();
            break;
          }
          case 16: {
            C = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            R = input.ReadInt32();
            break;
          }
          case 16: {
            C = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TaskObjectiveQuiz : pb::IMessage<TaskObjectiveQuiz>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TaskObjectiveQuiz> _parser = new pb::MessageParser<TaskObjectiveQuiz>(() => new TaskObjectiveQuiz());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TaskObjectiveQuiz> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bian.TaskReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskObjectiveQuiz() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskObjectiveQuiz(TaskObjectiveQuiz other) : this() {
      quizType_ = other.quizType_;
      quizNum_ = other.quizNum_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskObjectiveQuiz Clone() {
      return new TaskObjectiveQuiz(this);
    }

    /// <summary>Field number for the "quiz_type" field.</summary>
    public const int QuizTypeFieldNumber = 1;
    private int quizType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int QuizType {
      get { return quizType_; }
      set {
        quizType_ = value;
      }
    }

    /// <summary>Field number for the "quiz_num" field.</summary>
    public const int QuizNumFieldNumber = 2;
    private int quizNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int QuizNum {
      get { return quizNum_; }
      set {
        quizNum_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TaskObjectiveQuiz);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TaskObjectiveQuiz other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (QuizType != other.QuizType) return false;
      if (QuizNum != other.QuizNum) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (QuizType != 0) hash ^= QuizType.GetHashCode();
      if (QuizNum != 0) hash ^= QuizNum.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (QuizType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(QuizType);
      }
      if (QuizNum != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(QuizNum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (QuizType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(QuizType);
      }
      if (QuizNum != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(QuizNum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (QuizType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(QuizType);
      }
      if (QuizNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(QuizNum);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TaskObjectiveQuiz other) {
      if (other == null) {
        return;
      }
      if (other.QuizType != 0) {
        QuizType = other.QuizType;
      }
      if (other.QuizNum != 0) {
        QuizNum = other.QuizNum;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            QuizType = input.ReadInt32();
            break;
          }
          case 16: {
            QuizNum = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            QuizType = input.ReadInt32();
            break;
          }
          case 16: {
            QuizNum = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TaskSetting : pb::IMessage<TaskSetting>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TaskSetting> _parser = new pb::MessageParser<TaskSetting>(() => new TaskSetting());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TaskSetting> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bian.TaskReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskSetting() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskSetting(TaskSetting other) : this() {
      kind_ = other.kind_;
      switch (other.DataCase) {
        case DataOneofCase.Num:
          Num = other.Num;
          break;
        case DataOneofCase.Item:
          Item = other.Item.Clone();
          break;
        case DataOneofCase.MonInfo:
          MonInfo = other.MonInfo.Clone();
          break;
        case DataOneofCase.TarPos:
          TarPos = other.TarPos.Clone();
          break;
        case DataOneofCase.QuizInfo:
          QuizInfo = other.QuizInfo.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskSetting Clone() {
      return new TaskSetting(this);
    }

    /// <summary>Field number for the "kind" field.</summary>
    public const int KindFieldNumber = 1;
    private global::Bian.TaskType kind_ = global::Bian.TaskType.TaskTypeUnknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bian.TaskType Kind {
      get { return kind_; }
      set {
        kind_ = value;
      }
    }

    /// <summary>Field number for the "num" field.</summary>
    public const int NumFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Num {
      get { return dataCase_ == DataOneofCase.Num ? (int) data_ : 0; }
      set {
        data_ = value;
        dataCase_ = DataOneofCase.Num;
      }
    }

    /// <summary>Field number for the "item" field.</summary>
    public const int ItemFieldNumber = 12;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bian.TaskObjectiveItem Item {
      get { return dataCase_ == DataOneofCase.Item ? (global::Bian.TaskObjectiveItem) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Item;
      }
    }

    /// <summary>Field number for the "mon_info" field.</summary>
    public const int MonInfoFieldNumber = 13;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bian.TaskObjectiveMonster MonInfo {
      get { return dataCase_ == DataOneofCase.MonInfo ? (global::Bian.TaskObjectiveMonster) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.MonInfo;
      }
    }

    /// <summary>Field number for the "tar_pos" field.</summary>
    public const int TarPosFieldNumber = 14;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bian.TaskObjectiveMoveTo TarPos {
      get { return dataCase_ == DataOneofCase.TarPos ? (global::Bian.TaskObjectiveMoveTo) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.TarPos;
      }
    }

    /// <summary>Field number for the "quiz_info" field.</summary>
    public const int QuizInfoFieldNumber = 15;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bian.TaskObjectiveQuiz QuizInfo {
      get { return dataCase_ == DataOneofCase.QuizInfo ? (global::Bian.TaskObjectiveQuiz) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.QuizInfo;
      }
    }

    private object data_;
    /// <summary>Enum of possible cases for the "data" oneof.</summary>
    public enum DataOneofCase {
      None = 0,
      Num = 11,
      Item = 12,
      MonInfo = 13,
      TarPos = 14,
      QuizInfo = 15,
    }
    private DataOneofCase dataCase_ = DataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataOneofCase DataCase {
      get { return dataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearData() {
      dataCase_ = DataOneofCase.None;
      data_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TaskSetting);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TaskSetting other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Kind != other.Kind) return false;
      if (Num != other.Num) return false;
      if (!object.Equals(Item, other.Item)) return false;
      if (!object.Equals(MonInfo, other.MonInfo)) return false;
      if (!object.Equals(TarPos, other.TarPos)) return false;
      if (!object.Equals(QuizInfo, other.QuizInfo)) return false;
      if (DataCase != other.DataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Kind != global::Bian.TaskType.TaskTypeUnknown) hash ^= Kind.GetHashCode();
      if (dataCase_ == DataOneofCase.Num) hash ^= Num.GetHashCode();
      if (dataCase_ == DataOneofCase.Item) hash ^= Item.GetHashCode();
      if (dataCase_ == DataOneofCase.MonInfo) hash ^= MonInfo.GetHashCode();
      if (dataCase_ == DataOneofCase.TarPos) hash ^= TarPos.GetHashCode();
      if (dataCase_ == DataOneofCase.QuizInfo) hash ^= QuizInfo.GetHashCode();
      hash ^= (int) dataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Kind != global::Bian.TaskType.TaskTypeUnknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Kind);
      }
      if (dataCase_ == DataOneofCase.Num) {
        output.WriteRawTag(88);
        output.WriteInt32(Num);
      }
      if (dataCase_ == DataOneofCase.Item) {
        output.WriteRawTag(98);
        output.WriteMessage(Item);
      }
      if (dataCase_ == DataOneofCase.MonInfo) {
        output.WriteRawTag(106);
        output.WriteMessage(MonInfo);
      }
      if (dataCase_ == DataOneofCase.TarPos) {
        output.WriteRawTag(114);
        output.WriteMessage(TarPos);
      }
      if (dataCase_ == DataOneofCase.QuizInfo) {
        output.WriteRawTag(122);
        output.WriteMessage(QuizInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Kind != global::Bian.TaskType.TaskTypeUnknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Kind);
      }
      if (dataCase_ == DataOneofCase.Num) {
        output.WriteRawTag(88);
        output.WriteInt32(Num);
      }
      if (dataCase_ == DataOneofCase.Item) {
        output.WriteRawTag(98);
        output.WriteMessage(Item);
      }
      if (dataCase_ == DataOneofCase.MonInfo) {
        output.WriteRawTag(106);
        output.WriteMessage(MonInfo);
      }
      if (dataCase_ == DataOneofCase.TarPos) {
        output.WriteRawTag(114);
        output.WriteMessage(TarPos);
      }
      if (dataCase_ == DataOneofCase.QuizInfo) {
        output.WriteRawTag(122);
        output.WriteMessage(QuizInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Kind != global::Bian.TaskType.TaskTypeUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Kind);
      }
      if (dataCase_ == DataOneofCase.Num) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Num);
      }
      if (dataCase_ == DataOneofCase.Item) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Item);
      }
      if (dataCase_ == DataOneofCase.MonInfo) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MonInfo);
      }
      if (dataCase_ == DataOneofCase.TarPos) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TarPos);
      }
      if (dataCase_ == DataOneofCase.QuizInfo) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(QuizInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TaskSetting other) {
      if (other == null) {
        return;
      }
      if (other.Kind != global::Bian.TaskType.TaskTypeUnknown) {
        Kind = other.Kind;
      }
      switch (other.DataCase) {
        case DataOneofCase.Num:
          Num = other.Num;
          break;
        case DataOneofCase.Item:
          if (Item == null) {
            Item = new global::Bian.TaskObjectiveItem();
          }
          Item.MergeFrom(other.Item);
          break;
        case DataOneofCase.MonInfo:
          if (MonInfo == null) {
            MonInfo = new global::Bian.TaskObjectiveMonster();
          }
          MonInfo.MergeFrom(other.MonInfo);
          break;
        case DataOneofCase.TarPos:
          if (TarPos == null) {
            TarPos = new global::Bian.TaskObjectiveMoveTo();
          }
          TarPos.MergeFrom(other.TarPos);
          break;
        case DataOneofCase.QuizInfo:
          if (QuizInfo == null) {
            QuizInfo = new global::Bian.TaskObjectiveQuiz();
          }
          QuizInfo.MergeFrom(other.QuizInfo);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Kind = (global::Bian.TaskType) input.ReadEnum();
            break;
          }
          case 88: {
            Num = input.ReadInt32();
            break;
          }
          case 98: {
            global::Bian.TaskObjectiveItem subBuilder = new global::Bian.TaskObjectiveItem();
            if (dataCase_ == DataOneofCase.Item) {
              subBuilder.MergeFrom(Item);
            }
            input.ReadMessage(subBuilder);
            Item = subBuilder;
            break;
          }
          case 106: {
            global::Bian.TaskObjectiveMonster subBuilder = new global::Bian.TaskObjectiveMonster();
            if (dataCase_ == DataOneofCase.MonInfo) {
              subBuilder.MergeFrom(MonInfo);
            }
            input.ReadMessage(subBuilder);
            MonInfo = subBuilder;
            break;
          }
          case 114: {
            global::Bian.TaskObjectiveMoveTo subBuilder = new global::Bian.TaskObjectiveMoveTo();
            if (dataCase_ == DataOneofCase.TarPos) {
              subBuilder.MergeFrom(TarPos);
            }
            input.ReadMessage(subBuilder);
            TarPos = subBuilder;
            break;
          }
          case 122: {
            global::Bian.TaskObjectiveQuiz subBuilder = new global::Bian.TaskObjectiveQuiz();
            if (dataCase_ == DataOneofCase.QuizInfo) {
              subBuilder.MergeFrom(QuizInfo);
            }
            input.ReadMessage(subBuilder);
            QuizInfo = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Kind = (global::Bian.TaskType) input.ReadEnum();
            break;
          }
          case 88: {
            Num = input.ReadInt32();
            break;
          }
          case 98: {
            global::Bian.TaskObjectiveItem subBuilder = new global::Bian.TaskObjectiveItem();
            if (dataCase_ == DataOneofCase.Item) {
              subBuilder.MergeFrom(Item);
            }
            input.ReadMessage(subBuilder);
            Item = subBuilder;
            break;
          }
          case 106: {
            global::Bian.TaskObjectiveMonster subBuilder = new global::Bian.TaskObjectiveMonster();
            if (dataCase_ == DataOneofCase.MonInfo) {
              subBuilder.MergeFrom(MonInfo);
            }
            input.ReadMessage(subBuilder);
            MonInfo = subBuilder;
            break;
          }
          case 114: {
            global::Bian.TaskObjectiveMoveTo subBuilder = new global::Bian.TaskObjectiveMoveTo();
            if (dataCase_ == DataOneofCase.TarPos) {
              subBuilder.MergeFrom(TarPos);
            }
            input.ReadMessage(subBuilder);
            TarPos = subBuilder;
            break;
          }
          case 122: {
            global::Bian.TaskObjectiveQuiz subBuilder = new global::Bian.TaskObjectiveQuiz();
            if (dataCase_ == DataOneofCase.QuizInfo) {
              subBuilder.MergeFrom(QuizInfo);
            }
            input.ReadMessage(subBuilder);
            QuizInfo = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 任务
  /// </summary>
  public sealed partial class Task : pb::IMessage<Task>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Task> _parser = new pb::MessageParser<Task>(() => new Task());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Task> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bian.TaskReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Task() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Task(Task other) : this() {
      id_ = other.id_;
      kind_ = other.kind_;
      setting_ = other.setting_ != null ? other.setting_.Clone() : null;
      rate_ = other.rate_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Task Clone() {
      return new Task(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    /// <summary>
    /// 任务 ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "kind" field.</summary>
    public const int KindFieldNumber = 2;
    private global::Bian.TaskType kind_ = global::Bian.TaskType.TaskTypeUnknown;
    /// <summary>
    /// 任务类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bian.TaskType Kind {
      get { return kind_; }
      set {
        kind_ = value;
      }
    }

    /// <summary>Field number for the "setting" field.</summary>
    public const int SettingFieldNumber = 3;
    private global::Bian.TaskSetting setting_;
    /// <summary>
    /// 配置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bian.TaskSetting Setting {
      get { return setting_; }
      set {
        setting_ = value;
      }
    }

    /// <summary>Field number for the "rate" field.</summary>
    public const int RateFieldNumber = 4;
    private int rate_;
    /// <summary>
    /// 进度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Rate {
      get { return rate_; }
      set {
        rate_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Task);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Task other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Kind != other.Kind) return false;
      if (!object.Equals(Setting, other.Setting)) return false;
      if (Rate != other.Rate) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Kind != global::Bian.TaskType.TaskTypeUnknown) hash ^= Kind.GetHashCode();
      if (setting_ != null) hash ^= Setting.GetHashCode();
      if (Rate != 0) hash ^= Rate.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Kind != global::Bian.TaskType.TaskTypeUnknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Kind);
      }
      if (setting_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Setting);
      }
      if (Rate != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Rate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Kind != global::Bian.TaskType.TaskTypeUnknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Kind);
      }
      if (setting_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Setting);
      }
      if (Rate != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Rate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Kind != global::Bian.TaskType.TaskTypeUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Kind);
      }
      if (setting_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Setting);
      }
      if (Rate != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Task other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Kind != global::Bian.TaskType.TaskTypeUnknown) {
        Kind = other.Kind;
      }
      if (other.setting_ != null) {
        if (setting_ == null) {
          Setting = new global::Bian.TaskSetting();
        }
        Setting.MergeFrom(other.Setting);
      }
      if (other.Rate != 0) {
        Rate = other.Rate;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Kind = (global::Bian.TaskType) input.ReadEnum();
            break;
          }
          case 26: {
            if (setting_ == null) {
              Setting = new global::Bian.TaskSetting();
            }
            input.ReadMessage(Setting);
            break;
          }
          case 32: {
            Rate = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Kind = (global::Bian.TaskType) input.ReadEnum();
            break;
          }
          case 26: {
            if (setting_ == null) {
              Setting = new global::Bian.TaskSetting();
            }
            input.ReadMessage(Setting);
            break;
          }
          case 32: {
            Rate = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TaskList : pb::IMessage<TaskList>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TaskList> _parser = new pb::MessageParser<TaskList>(() => new TaskList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TaskList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bian.TaskReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskList(TaskList other) : this() {
      id_ = other.id_;
      kind_ = other.kind_;
      rate_ = other.rate_;
      curTask_ = other.curTask_ != null ? other.curTask_.Clone() : null;
      receiveReward_ = other.receiveReward_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskList Clone() {
      return new TaskList(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    /// <summary>
    /// task list id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "kind" field.</summary>
    public const int KindFieldNumber = 2;
    private global::Bian.TaskListType kind_ = global::Bian.TaskListType.TaskListTypeUnknown;
    /// <summary>
    /// task list type
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bian.TaskListType Kind {
      get { return kind_; }
      set {
        kind_ = value;
      }
    }

    /// <summary>Field number for the "rate" field.</summary>
    public const int RateFieldNumber = 3;
    private int rate_;
    /// <summary>
    /// 进度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Rate {
      get { return rate_; }
      set {
        rate_ = value;
      }
    }

    /// <summary>Field number for the "cur_task" field.</summary>
    public const int CurTaskFieldNumber = 4;
    private global::Bian.Task curTask_;
    /// <summary>
    /// current task
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bian.Task CurTask {
      get { return curTask_; }
      set {
        curTask_ = value;
      }
    }

    /// <summary>Field number for the "receive_reward" field.</summary>
    public const int ReceiveRewardFieldNumber = 5;
    private int receiveReward_;
    /// <summary>
    /// 记录领取奖励的任务rate时间点，0表示未曾领取奖励
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ReceiveReward {
      get { return receiveReward_; }
      set {
        receiveReward_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TaskList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TaskList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Kind != other.Kind) return false;
      if (Rate != other.Rate) return false;
      if (!object.Equals(CurTask, other.CurTask)) return false;
      if (ReceiveReward != other.ReceiveReward) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Kind != global::Bian.TaskListType.TaskListTypeUnknown) hash ^= Kind.GetHashCode();
      if (Rate != 0) hash ^= Rate.GetHashCode();
      if (curTask_ != null) hash ^= CurTask.GetHashCode();
      if (ReceiveReward != 0) hash ^= ReceiveReward.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Kind != global::Bian.TaskListType.TaskListTypeUnknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Kind);
      }
      if (Rate != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Rate);
      }
      if (curTask_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(CurTask);
      }
      if (ReceiveReward != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ReceiveReward);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Kind != global::Bian.TaskListType.TaskListTypeUnknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Kind);
      }
      if (Rate != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Rate);
      }
      if (curTask_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(CurTask);
      }
      if (ReceiveReward != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ReceiveReward);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Kind != global::Bian.TaskListType.TaskListTypeUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Kind);
      }
      if (Rate != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rate);
      }
      if (curTask_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CurTask);
      }
      if (ReceiveReward != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReceiveReward);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TaskList other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Kind != global::Bian.TaskListType.TaskListTypeUnknown) {
        Kind = other.Kind;
      }
      if (other.Rate != 0) {
        Rate = other.Rate;
      }
      if (other.curTask_ != null) {
        if (curTask_ == null) {
          CurTask = new global::Bian.Task();
        }
        CurTask.MergeFrom(other.CurTask);
      }
      if (other.ReceiveReward != 0) {
        ReceiveReward = other.ReceiveReward;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Kind = (global::Bian.TaskListType) input.ReadEnum();
            break;
          }
          case 24: {
            Rate = input.ReadInt32();
            break;
          }
          case 34: {
            if (curTask_ == null) {
              CurTask = new global::Bian.Task();
            }
            input.ReadMessage(CurTask);
            break;
          }
          case 40: {
            ReceiveReward = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Kind = (global::Bian.TaskListType) input.ReadEnum();
            break;
          }
          case 24: {
            Rate = input.ReadInt32();
            break;
          }
          case 34: {
            if (curTask_ == null) {
              CurTask = new global::Bian.Task();
            }
            input.ReadMessage(CurTask);
            break;
          }
          case 40: {
            ReceiveReward = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 用户已接任务列表
  /// </summary>
  public sealed partial class PlayerTask : pb::IMessage<PlayerTask>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerTask> _parser = new pb::MessageParser<PlayerTask>(() => new PlayerTask());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerTask> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bian.TaskReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerTask() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerTask(PlayerTask other) : this() {
      taskLists_ = other.taskLists_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerTask Clone() {
      return new PlayerTask(this);
    }

    /// <summary>Field number for the "task_lists" field.</summary>
    public const int TaskListsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Bian.TaskList> _repeated_taskLists_codec
        = pb::FieldCodec.ForMessage(10, global::Bian.TaskList.Parser);
    private readonly pbc::RepeatedField<global::Bian.TaskList> taskLists_ = new pbc::RepeatedField<global::Bian.TaskList>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Bian.TaskList> TaskLists {
      get { return taskLists_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerTask);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerTask other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!taskLists_.Equals(other.taskLists_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= taskLists_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      taskLists_.WriteTo(output, _repeated_taskLists_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      taskLists_.WriteTo(ref output, _repeated_taskLists_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += taskLists_.CalculateSize(_repeated_taskLists_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerTask other) {
      if (other == null) {
        return;
      }
      taskLists_.Add(other.taskLists_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            taskLists_.AddEntriesFrom(input, _repeated_taskLists_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            taskLists_.AddEntriesFrom(ref input, _repeated_taskLists_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
